export type DiscoveryWindow = "June 6-24" | "Sep 1-12" | "Both windows";

export type DiscoveryKind =
  | "Nature"
  | "City"
  | "Food"
  | "Road Trip"
  | "Island"
  | "Culture"
  | "Hiking";

export interface DiscoveryPlace {
  id: string;
  title: string;
  country: string;
  region: string;
  bestWindow: DiscoveryWindow;
  idealLength: string;
  kind: DiscoveryKind;
  tags: string[];
  summary: string;
  whyGo: string;
  estimatedBudgetCad: string;
  flightNote: string;
  googleMapsQuery: string;
  imageUrl: string;
  imageAlt: string;
  imageCredit?: string;
  imageCreditUrl?: string;
  imageLicense?: string;
}

const commonsFile = (fileName: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(fileName)}?width=1200`;

const wikimedia = (
  fileName: string,
  imageAlt: string,
  imageCredit: string,
  imageCreditUrl: string,
  imageLicense: string,
) => ({
  imageUrl: commonsFile(fileName),
  imageAlt,
  imageCredit,
  imageCreditUrl,
  imageLicense,
});

export const discoveryWindows: Array<"All" | DiscoveryWindow> = ["All", "June 6-24", "Sep 1-12", "Both windows"];

export const discoveryKinds: Array<"All" | DiscoveryKind> = [
  "All",
  "Nature",
  "City",
  "Food",
  "Road Trip",
  "Island",
  "Culture",
  "Hiking",
];

export const discoveryPlaces: DiscoveryPlace[] = [
  {
    id: "discovery-azores",
    title: "Azores island loop",
    country: "Portugal",
    region: "Sao Miguel, Pico, Faial",
    bestWindow: "Both windows",
    idealLength: "8-12 days",
    kind: "Island",
    tags: ["volcanic lakes", "whale watching", "hot springs"],
    summary: "Green crater lakes, coastal drives, thermal pools, and slower island days.",
    whyGo: "Works beautifully when you want nature without a huge city itinerary.",
    estimatedBudgetCad: "$2,600-4,200",
    flightNote: "Usually easiest with a connection through Lisbon or Ponta Delgada routing.",
    googleMapsQuery: "Sete Cidades Azores Portugal",
    ...wikimedia(
      "Lagoa Das Sete Cidades Azores (235848553).jpeg",
      "Sete Cidades crater lakes in the Azores.",
      "F Mira via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Lagoa_das_Sete_Cidades_from_Vista_do_Rei.jpg",
      "CC BY-SA 4.0",
    ),
  },
  {
    id: "discovery-madeira",
    title: "Madeira hiking and coast",
    country: "Portugal",
    region: "Funchal, Pico do Arieiro, north coast",
    bestWindow: "Both windows",
    idealLength: "7-10 days",
    kind: "Hiking",
    tags: ["levada walks", "mountains", "ocean views"],
    summary: "Big ridge views, compact drives, and enough town life to keep evenings easy.",
    whyGo: "A strong pick if you want hikes, scenery, and minimal planning friction.",
    estimatedBudgetCad: "$2,400-3,900",
    flightNote: "Usually connects through Lisbon or Porto.",
    googleMapsQuery: "Pico do Arieiro Madeira Portugal",
    ...wikimedia(
      "View from Miradouro do Pico do Arieiro - Madeira 01.jpg",
      "Mountain landscape around Pico do Arieiro in Madeira.",
      "Bjørn Christian Tørrissen via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Pico_do_Arieiro_Madeira_Portugal_2014.jpg",
      "CC BY-SA 3.0",
    ),
  },
  {
    id: "discovery-iceland",
    title: "Iceland south coast",
    country: "Iceland",
    region: "Reykjavik, Vik, Jokulsarlon",
    bestWindow: "June 6-24",
    idealLength: "7-10 days",
    kind: "Road Trip",
    tags: ["waterfalls", "glaciers", "long daylight"],
    summary: "Waterfalls, black sand beaches, glacier lagoons, and very long June days.",
    whyGo: "June gives you room to move without racing daylight.",
    estimatedBudgetCad: "$3,800-6,000",
    flightNote: "Direct or one-stop routings are often practical from Toronto.",
    googleMapsQuery: "Seljalandsfoss Iceland south coast",
    ...wikimedia(
      "Seljalandsfoss, Suðurland, Islandia, 2014-08-16, DD 189-191 HDR.JPG",
      "Seljalandsfoss waterfall in Iceland.",
      "Diego Delso via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Seljalandsfoss,_Iceland,_2014-08-16,_DD_186-188_HDR.JPG",
      "CC BY-SA 4.0",
    ),
  },
  {
    id: "discovery-banff",
    title: "Banff and Jasper",
    country: "Canada",
    region: "Alberta Rockies",
    bestWindow: "June 6-24",
    idealLength: "7-12 days",
    kind: "Nature",
    tags: ["lakes", "mountains", "road trip"],
    summary: "Classic Canadian mountain trip: lakes, viewpoints, short hikes, and scenic drives.",
    whyGo: "June can be gorgeous before peak summer crowds fully hit.",
    estimatedBudgetCad: "$2,500-4,600",
    flightNote: "Fly to Calgary, rent a car, and keep the route simple.",
    googleMapsQuery: "Moraine Lake Banff National Park Alberta",
    ...wikimedia(
      "Moraine Lake 17092005.jpg",
      "Moraine Lake in Banff National Park.",
      "Gorgo via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Moraine_Lake_17092005.jpg",
      "Public domain",
    ),
  },
  {
    id: "discovery-newfoundland",
    title: "Newfoundland west coast",
    country: "Canada",
    region: "Gros Morne, Twillingate, St. John's",
    bestWindow: "June 6-24",
    idealLength: "8-12 days",
    kind: "Road Trip",
    tags: ["coast", "icebergs", "small towns"],
    summary: "A rugged Atlantic route with cliffs, fjords, small towns, and big quiet.",
    whyGo: "June is good for a raw, coastal trip with a real sense of distance.",
    estimatedBudgetCad: "$2,300-4,200",
    flightNote: "Fly into Deer Lake or St. John's, then rent a car.",
    googleMapsQuery: "Gros Morne National Park Newfoundland",
    ...wikimedia(
      "Gros Morne NP westernbrookpond2.jpg",
      "Western Brook Pond in Gros Morne National Park.",
      "Bert Pronk via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Western_Brook_Pond_fjord,_Gros_Morne_National_Park.jpg",
      "CC BY-SA 3.0",
    ),
  },
  {
    id: "discovery-vancouver-island",
    title: "Vancouver Island slow coast",
    country: "Canada",
    region: "Victoria, Tofino, Ucluelet",
    bestWindow: "Both windows",
    idealLength: "7-10 days",
    kind: "Nature",
    tags: ["beaches", "forest", "food"],
    summary: "Rainforest walks, beach towns, seafood, and a slower west-coast reset.",
    whyGo: "Good if you want Canada, nature, and comfort without a huge time-zone jump.",
    estimatedBudgetCad: "$2,400-4,300",
    flightNote: "Fly to Victoria or Vancouver, then ferry or connect onward.",
    googleMapsQuery: "Tofino Vancouver Island British Columbia",
    ...wikimedia(
      "Long Beach Panorama - Pacific Rim National Park - Vancouver Island BC - Canada - 02.jpg",
      "Long Beach in Pacific Rim National Park Reserve.",
      "Lhb1239 via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Long_Beach,_Pacific_Rim_National_Park.jpg",
      "CC BY-SA 3.0",
    ),
  },
  {
    id: "discovery-dolomites",
    title: "Dolomites hut-and-lake route",
    country: "Italy",
    region: "Cortina, Val Gardena, Tre Cime",
    bestWindow: "Sep 1-12",
    idealLength: "8-12 days",
    kind: "Hiking",
    tags: ["mountains", "lakes", "scenic drives"],
    summary: "Alpine lakes, dramatic ridgelines, cable cars, and mountain towns.",
    whyGo: "Early September is a sweet spot for hiking without peak August pressure.",
    estimatedBudgetCad: "$3,200-5,400",
    flightNote: "Fly into Venice, Munich, or Milan, then rent a car or use buses.",
    googleMapsQuery: "Tre Cime di Lavaredo Dolomites Italy",
    ...wikimedia(
      "Drei Zinnen Tre Cime di Lavaredo Dolomites.jpg",
      "Tre Cime di Lavaredo in the Dolomites.",
      "Taxiarchos228 via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Drei_Zinnen_Lavaredo_2013.jpg",
      "CC BY-SA 3.0",
    ),
  },
  {
    id: "discovery-slovenia",
    title: "Slovenia lakes and Ljubljana",
    country: "Slovenia",
    region: "Ljubljana, Lake Bled, Soca Valley",
    bestWindow: "Sep 1-12",
    idealLength: "7-10 days",
    kind: "Road Trip",
    tags: ["lakes", "small capital", "mountains"],
    summary: "A compact route with a charming capital, lakes, gorges, and mountain drives.",
    whyGo: "Easy to make beautiful without overcomplicating the route.",
    estimatedBudgetCad: "$2,600-4,300",
    flightNote: "Often works via Vienna, Munich, Venice, or Zagreb.",
    googleMapsQuery: "Lake Bled Slovenia",
    ...wikimedia(
      "Bled Castle 05.jpg",
      "Lake Bled and Bled Castle in Slovenia.",
      "Jean-Pierre Dalbera via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Bled_Castle_05.jpg",
      "CC BY 2.0",
    ),
  },
  {
    id: "discovery-croatia",
    title: "Croatia coast without rushing",
    country: "Croatia",
    region: "Split, Hvar, Dubrovnik",
    bestWindow: "Sep 1-12",
    idealLength: "8-12 days",
    kind: "Island",
    tags: ["coast", "old towns", "swimming"],
    summary: "Blue water, stone towns, ferries, and lazy evenings by the coast.",
    whyGo: "September keeps the summer feeling but usually softens the crowds.",
    estimatedBudgetCad: "$3,000-5,200",
    flightNote: "Usually connect through a European hub into Split or Dubrovnik.",
    googleMapsQuery: "Dubrovnik old town Croatia",
    ...wikimedia(
      "Dubrovnik Old Town 1.jpg",
      "Dubrovnik old town viewed from the city walls.",
      "Diego Delso via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Dubrovnik_old_town_-_view_from_city_walls.jpg",
      "CC BY-SA 4.0",
    ),
  },
  {
    id: "discovery-scotland",
    title: "Scotland Highlands loop",
    country: "United Kingdom",
    region: "Edinburgh, Glencoe, Isle of Skye",
    bestWindow: "Both windows",
    idealLength: "8-12 days",
    kind: "Road Trip",
    tags: ["castles", "highlands", "moody landscapes"],
    summary: "A cinematic road trip with old cities, valleys, islands, and weather that becomes part of it.",
    whyGo: "Good if you want atmosphere, driving, and history in one trip.",
    estimatedBudgetCad: "$3,200-5,600",
    flightNote: "Fly to Edinburgh or Glasgow, then rent a car for the Highlands.",
    googleMapsQuery: "Glencoe Scotland Highlands",
    ...wikimedia(
      "Glencoe, Scotland.jpg",
      "Landscape in Glencoe, Scotland.",
      "Magnus Hagdorn via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Glencoe,_Scotland.jpg",
      "CC BY-SA 2.0",
    ),
  },
  {
    id: "discovery-hokkaido",
    title: "Hokkaido late-summer north",
    country: "Japan",
    region: "Sapporo, Biei, Daisetsuzan",
    bestWindow: "Sep 1-12",
    idealLength: "8-12 days",
    kind: "Nature",
    tags: ["cooler weather", "food", "wide landscapes"],
    summary: "Cooler air, big landscapes, seafood, and a very different side of Japan.",
    whyGo: "A strong choice if September Japan still feels tempting but Tokyo heat does not.",
    estimatedBudgetCad: "$3,200-5,300",
    flightNote: "Fly into Tokyo, then connect to Sapporo.",
    googleMapsQuery: "Biei Hokkaido Japan",
    ...wikimedia(
      "Shirogane Blue Pond, Biei, Hokkaido Japan.jpg",
      "Blue Pond in Biei, Hokkaido.",
      "663highland via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Blue_Pond_Biei_Hokkaido_Japan.jpg",
      "CC BY 2.5",
    ),
  },
  {
    id: "discovery-seoul",
    title: "Seoul food and neighborhoods",
    country: "South Korea",
    region: "Seoul, DMZ or Jeonju side trip",
    bestWindow: "Sep 1-12",
    idealLength: "7-10 days",
    kind: "City",
    tags: ["food", "cafes", "shopping"],
    summary: "Dense neighborhoods, late nights, markets, palaces, and very good food days.",
    whyGo: "Good if you want city energy without building a complicated multi-country route.",
    estimatedBudgetCad: "$2,700-4,600",
    flightNote: "Usually one-stop from Toronto, sometimes direct depending on dates.",
    googleMapsQuery: "Bukchon Hanok Village Seoul South Korea",
    ...wikimedia(
      "Bukchon Hanok Village 03.jpg",
      "Traditional houses in Bukchon Hanok Village, Seoul.",
      "Republic of Korea via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Bukchon_Hanok_Village_2014.jpg",
      "CC BY-SA 2.0",
    ),
  },
  {
    id: "discovery-mexico-city",
    title: "Mexico City and Oaxaca",
    country: "Mexico",
    region: "CDMX, Puebla, Oaxaca",
    bestWindow: "Both windows",
    idealLength: "8-12 days",
    kind: "Food",
    tags: ["food", "museums", "architecture"],
    summary: "A food-forward city trip with museums, neighborhoods, markets, and a strong Oaxaca extension.",
    whyGo: "High reward without a brutal flight plan from Toronto.",
    estimatedBudgetCad: "$2,200-4,000",
    flightNote: "Direct flights to Mexico City are common from Toronto.",
    googleMapsQuery: "Roma Norte Mexico City",
    ...wikimedia(
      "Palacio de Bellas Artes, Mexico City.jpg",
      "Palacio de Bellas Artes in Mexico City.",
      "Xavier via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Palacio_de_Bellas_Artes,_Mexico_City.jpg",
      "CC BY-SA 2.0",
    ),
  },
  {
    id: "discovery-morocco",
    title: "Morocco cities and desert edge",
    country: "Morocco",
    region: "Marrakech, Fes, Sahara edge",
    bestWindow: "Sep 1-12",
    idealLength: "9-12 days",
    kind: "Culture",
    tags: ["markets", "riads", "desert"],
    summary: "Medinas, courtyards, mountain roads, and a desert-edge reset if you have enough days.",
    whyGo: "September is more realistic than deep summer for heat.",
    estimatedBudgetCad: "$2,800-4,800",
    flightNote: "Usually connects through Europe or Montreal.",
    googleMapsQuery: "Jemaa el-Fnaa Marrakech Morocco",
    ...wikimedia(
      "Jemaa el-Fnaa at night.jpg",
      "Jemaa el-Fnaa square in Marrakech at night.",
      "Bjørn Christian Tørrissen via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Jemaa_el-Fnaa_at_night.jpg",
      "CC BY-SA 3.0",
    ),
  },
  {
    id: "discovery-cappadocia",
    title: "Istanbul and Cappadocia",
    country: "Turkiye",
    region: "Istanbul, Goreme, Cappadocia",
    bestWindow: "Sep 1-12",
    idealLength: "8-11 days",
    kind: "Culture",
    tags: ["old city", "balloons", "food"],
    summary: "A huge city start followed by cave hotels, valleys, and early balloon mornings.",
    whyGo: "A good mix of history, food, and surreal landscapes in one route.",
    estimatedBudgetCad: "$2,900-5,000",
    flightNote: "Fly to Istanbul, then domestic flight to Cappadocia.",
    googleMapsQuery: "Goreme Cappadocia Turkiye",
    ...wikimedia(
      "Hot air balloon in Cappadocia 01.jpg",
      "Hot air balloons over Cappadocia.",
      "Benh LIEU SONG via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Hot_air_ballooning_in_Cappadocia.jpg",
      "CC BY-SA 3.0",
    ),
  },
  {
    id: "discovery-greece",
    title: "Athens and Cyclades",
    country: "Greece",
    region: "Athens, Naxos, Paros, Santorini",
    bestWindow: "Sep 1-12",
    idealLength: "8-12 days",
    kind: "Island",
    tags: ["islands", "swimming", "old towns"],
    summary: "A classic island route with enough time for beaches, ferries, and slow evenings.",
    whyGo: "September keeps the water warm and the itinerary easier than peak summer.",
    estimatedBudgetCad: "$3,200-5,800",
    flightNote: "Fly into Athens, then use ferries or short domestic flights.",
    googleMapsQuery: "Naxos Greece Cyclades",
    ...wikimedia(
      "Naxos Νάξος Chora 2020-08-20 28 Portara Πορτάρα.jpg",
      "Portara landmark on Naxos in Greece.",
      "Zde via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Naxos_Portara_2010.jpg",
      "CC BY-SA 4.0",
    ),
  },
  {
    id: "discovery-portugal-mainland",
    title: "Lisbon, Porto, and Douro",
    country: "Portugal",
    region: "Lisbon, Porto, Douro Valley",
    bestWindow: "Both windows",
    idealLength: "8-11 days",
    kind: "City",
    tags: ["food", "tiles", "wine country"],
    summary: "Easy cities, good food, day trips, tiled streets, and a scenic Douro add-on.",
    whyGo: "Low-friction Europe if you want beauty without overengineering the trip.",
    estimatedBudgetCad: "$2,700-4,700",
    flightNote: "Direct flights to Lisbon or Porto are often available from Toronto.",
    googleMapsQuery: "Porto Ribeira Portugal Douro",
    ...wikimedia(
      "Cais da Ribeira in Porto (5).jpg",
      "Ribeira district in Porto, Portugal.",
      "Deensel via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Ribeira_Porto_Portugal.jpg",
      "CC BY 2.0",
    ),
  },
  {
    id: "discovery-faroe",
    title: "Faroe Islands road trip",
    country: "Faroe Islands",
    region: "Vagar, Streymoy, Eysturoy",
    bestWindow: "June 6-24",
    idealLength: "7-10 days",
    kind: "Nature",
    tags: ["cliffs", "villages", "moody weather"],
    summary: "Tiny villages, cliffs, tunnels, sheep roads, and dramatic weather.",
    whyGo: "For a visually wild trip where the landscape is the main event.",
    estimatedBudgetCad: "$3,600-5,800",
    flightNote: "Usually connect through Copenhagen, Reykjavik, or Edinburgh.",
    googleMapsQuery: "Gasadalur Faroe Islands",
    ...wikimedia(
      "Waterfall at Gasadalur, Faroe Islands.jpg",
      "Gasadalur village and waterfall in the Faroe Islands.",
      "Erik Christensen via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Gasadalur,_Faroe_Islands.jpg",
      "CC BY-SA 3.0",
    ),
  },
  {
    id: "discovery-oregon",
    title: "Oregon coast and Portland",
    country: "United States",
    region: "Portland, Cannon Beach, Bend",
    bestWindow: "Both windows",
    idealLength: "7-10 days",
    kind: "Road Trip",
    tags: ["coast", "coffee", "forests"],
    summary: "Coastal drives, good coffee, easy food days, forests, and a Bend add-on.",
    whyGo: "A relaxed North America option with strong scenery and city breaks.",
    estimatedBudgetCad: "$2,500-4,400",
    flightNote: "Fly to Portland or Seattle, then rent a car.",
    googleMapsQuery: "Cannon Beach Oregon",
    ...wikimedia(
      "Cannon Beach October 2019 001.jpg",
      "Haystack Rock at Cannon Beach, Oregon.",
      "Finetooth via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Haystack_Rock,_Cannon_Beach,_Oregon.jpg",
      "CC BY-SA 3.0",
    ),
  },
];
