export type JapanExploreKind =
  | "Food"
  | "Restaurants"
  | "Neighborhoods"
  | "Temples"
  | "Museums"
  | "Shopping"
  | "Nightlife"
  | "Rainy Day"
  | "Day Trips"
  | "Branch Ideas";

export type JapanPhotoStatus = "wikimedia" | "fallback" | "replace-later";

export interface JapanExplorePlace {
  id: string;
  title: string;
  city: string;
  region: string;
  neighborhood: string;
  kind: JapanExploreKind;
  tags: string[];
  description: string;
  whyGo: string;
  estimatedCostJpy: number;
  googleMapsQuery: string;
  imageUrl: string;
  imageAlt: string;
  imageCredit?: string;
  imageCreditUrl?: string;
  imageLicense?: string;
  imageSearchQuery: string;
  photoStatus: JapanPhotoStatus;
  recommendedTime?: string;
}

const commonsFile = (fileName: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(fileName)}?width=1200`;

const fallback = (label: string) => ({
  imageUrl: "",
  imageAlt: `Compact generated visual for ${label}.`,
  photoStatus: "fallback" as const,
});

const wikimedia = (
  fileName: string,
  imageAlt: string,
  imageCredit: string,
  imageCreditUrl: string,
  imageLicense: string,
) => ({
  imageUrl: commonsFile(fileName),
  imageAlt,
  imageCredit,
  imageCreditUrl,
  imageLicense,
  photoStatus: "wikimedia" as const,
});

const p = (place: JapanExplorePlace) => place;

export const japanExploreKinds: Array<"All" | JapanExploreKind> = [
  "All",
  "Food",
  "Restaurants",
  "Neighborhoods",
  "Temples",
  "Museums",
  "Shopping",
  "Nightlife",
  "Rainy Day",
  "Day Trips",
  "Branch Ideas",
];

export const japanExplorePlaces: JapanExplorePlace[] = [
  p({
    id: "idea-shibuya-crossing",
    title: "Shibuya Crossing and Center Gai",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Shibuya",
    kind: "Neighborhoods",
    tags: ["first night", "lights", "city energy"],
    description: "The Tokyo overload moment: crowds, screens, and streets that never really pause.",
    whyGo: "Good first-night energy if jet lag lets you stay awake.",
    estimatedCostJpy: 1000,
    googleMapsQuery: "Shibuya Crossing Tokyo Japan",
    ...wikimedia(
      "Tokyo Shibuya Scramble Crossing 2018-10-09.jpg",
      "Crowds crossing Shibuya Scramble Crossing in Tokyo.",
      "Benh LIEU SONG via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Tokyo_Shibuya_Scramble_Crossing_2018-10-09.jpg",
      "CC BY-SA 2.0",
    ),
    imageSearchQuery: "Shibuya Crossing Tokyo night",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-shinjuku-night",
    title: "Omoide Yokocho and Golden Gai",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Shinjuku",
    kind: "Nightlife",
    tags: ["tiny bars", "counter food", "night"],
    description: "Tiny lanes, small counters, and the kind of Tokyo night that feels better loose.",
    whyGo: "Go for atmosphere and a few bites, not a checklist.",
    estimatedCostJpy: 7000,
    googleMapsQuery: "Omoide Yokocho Golden Gai Shinjuku Tokyo",
    ...wikimedia(
      "Colorful neon street signs in Kabukichō, Shinjuku, Tokyo.jpg",
      "Neon signs in Kabukicho, Shinjuku at night.",
      "Basile Morin via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Colorful_neon_street_signs_in_Kabukich%C5%8D,_Shinjuku,_Tokyo.jpg",
      "CC BY-SA 4.0",
    ),
    imageSearchQuery: "Shinjuku Tokyo neon night",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-sensoji",
    title: "Senso-ji and Asakusa snack lanes",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Asakusa",
    kind: "Temples",
    tags: ["old Tokyo", "snacks", "classic"],
    description: "Temple gates, snack stalls, and an easy way to start a slower Tokyo morning.",
    whyGo: "Best early or after dinner when the main approach calms down.",
    estimatedCostJpy: 1500,
    googleMapsQuery: "Senso-ji Asakusa Tokyo Japan",
    ...wikimedia(
      "Five-storied Pagoda, Sensoji, Tokyo, 20240824 1103 5616.jpg",
      "Five-storied pagoda at Senso-ji in Tokyo.",
      "Jakub Halun via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Five-storied_Pagoda,_Sensoji,_Tokyo,_20240824_1103_5616.jpg",
      "CC BY 4.0",
    ),
    imageSearchQuery: "Senso-ji temple Tokyo",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-tsukiji-breakfast",
    title: "Tsukiji Outer Market breakfast crawl",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Tsukiji",
    kind: "Food",
    tags: ["breakfast", "market", "seafood"],
    description: "Graze slowly and leave before the midday crowd squeezes the lanes.",
    whyGo: "Useful food morning without needing a reservation.",
    estimatedCostJpy: 4500,
    googleMapsQuery: "Tsukiji Outer Market Tokyo breakfast",
    ...wikimedia(
      "Tsukiji Outer Market -04.jpg",
      "Tsukiji Outer Market street stalls in Tokyo.",
      "Aimaimyi via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Tsukiji_Outer_Market_-04.jpg",
      "CC BY-SA 3.0",
    ),
    imageSearchQuery: "Tsukiji Outer Market Tokyo",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-akihabara-arcades",
    title: "Akihabara arcades and hobby shops",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Akihabara",
    kind: "Shopping",
    tags: ["games", "anime", "electronics"],
    description: "Games, figures, electronics, and wandering without pretending it is subtle.",
    whyGo: "Set a spending cap before you start browsing.",
    estimatedCostJpy: 5000,
    googleMapsQuery: "Akihabara arcades hobby shops Tokyo",
    ...wikimedia(
      "Claw cranes with kawaii stuffed mascots and a woman playing, Akihabara, Chiyoda, Tokyo, Japan.jpg",
      "Arcade claw machines in Akihabara, Tokyo.",
      "Basile Morin via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Claw_cranes_with_kawaii_stuffed_mascots_and_a_woman_playing,_Akihabara,_Chiyoda,_Tokyo,_Japan.jpg",
      "CC BY-SA 4.0",
    ),
    imageSearchQuery: "Akihabara Tokyo arcades",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-harajuku-meiji",
    title: "Meiji Shrine, Harajuku, and Omotesando",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Harajuku",
    kind: "Neighborhoods",
    tags: ["shrine", "fashion", "first morning"],
    description: "A calm shrine reset beside a louder fashion-and-snack neighborhood.",
    whyGo: "Easy to tune up or down depending on energy.",
    estimatedCostJpy: 1500,
    googleMapsQuery: "Meiji Shrine Harajuku Omotesando Tokyo",
    ...wikimedia(
      "Takeshita Street entrance on Meiji Avenue side.jpg",
      "Entrance to Takeshita Street in Harajuku.",
      "Syced via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Takeshita_Street_entrance_on_Meiji_Avenue_side.jpg",
      "CC0",
    ),
    imageSearchQuery: "Harajuku Takeshita Street Tokyo",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-teamlab",
    title: "teamLab Planets",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Toyosu",
    kind: "Rainy Day",
    tags: ["indoor", "timed ticket", "visual"],
    description: "A polished indoor break when Tokyo weather gets sticky or rainy.",
    whyGo: "Book a slot if it becomes a priority. Photos need official/API sourcing later.",
    estimatedCostJpy: 4500,
    googleMapsQuery: "teamLab Planets Toyosu Tokyo",
    ...fallback("teamLab Planets"),
    imageSearchQuery: "teamLab Planets Tokyo official photo",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-ghibli",
    title: "Ghibli Museum, Mitaka",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Mitaka",
    kind: "Museums",
    tags: ["animation", "reservation", "quiet"],
    description: "Small, charming, and mostly about whether the ticket hunt is worth it.",
    whyGo: "Cheap ticket, hard reservation. Decide early.",
    estimatedCostJpy: 1000,
    googleMapsQuery: "Ghibli Museum Mitaka Tokyo",
    ...fallback("Ghibli Museum"),
    imageSearchQuery: "Ghibli Museum Mitaka exterior",
    recommendedTime: "midday",
  }),
  p({
    id: "idea-ginza-depachika",
    title: "Ginza depachika food halls",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Ginza",
    kind: "Food",
    tags: ["rainy day", "snacks", "shopping"],
    description: "Basement food floors for snacks, gifts, and low-effort dinner fixes.",
    whyGo: "A strong rainy-day swap when outdoor plans feel annoying.",
    estimatedCostJpy: 3500,
    googleMapsQuery: "Ginza depachika food hall Tokyo",
    ...fallback("Ginza depachika food halls"),
    imageSearchQuery: "Ginza depachika Tokyo food hall",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-shimokitazawa",
    title: "Shimokitazawa vintage and cafes",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Shimokitazawa",
    kind: "Shopping",
    tags: ["vintage", "coffee", "loose day"],
    description: "A slower Tokyo idea for clothes, cafes, and a break from giant-station energy.",
    whyGo: "Good when you want Tokyo without another landmark.",
    estimatedCostJpy: 5000,
    googleMapsQuery: "Shimokitazawa vintage shops cafes Tokyo",
    ...fallback("Shimokitazawa"),
    imageSearchQuery: "Shimokitazawa Tokyo vintage shops",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-nakameguro-daikanyama",
    title: "Nakameguro and Daikanyama design walk",
    city: "Tokyo",
    region: "Kanto",
    neighborhood: "Nakameguro",
    kind: "Neighborhoods",
    tags: ["coffee", "design", "books"],
    description: "Coffee, books, clothes, and a quieter version of stylish Tokyo.",
    whyGo: "Works as a flexible half-day before a big evening.",
    estimatedCostJpy: 6000,
    googleMapsQuery: "Nakameguro Daikanyama Tokyo design stores cafes",
    ...fallback("Nakameguro and Daikanyama"),
    imageSearchQuery: "Nakameguro Daikanyama Tokyo",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-fushimi-inari",
    title: "Fushimi Inari early gates",
    city: "Kyoto",
    region: "Kansai",
    neighborhood: "Fushimi",
    kind: "Temples",
    tags: ["early start", "torii", "classic"],
    description: "Worth doing early. Even a partial climb is enough.",
    whyGo: "The crowd changes the whole feeling, so timing matters.",
    estimatedCostJpy: 500,
    googleMapsQuery: "Fushimi Inari Taisha Kyoto",
    ...wikimedia(
      "Torii path with lantern at Fushimi Inari Taisha Shrine, Kyoto, Japan.jpg",
      "Torii path at Fushimi Inari Taisha in Kyoto.",
      "Basile Morin via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine,_Kyoto,_Japan.jpg",
      "CC BY-SA 4.0",
    ),
    imageSearchQuery: "Fushimi Inari Kyoto torii",
    recommendedTime: "early morning",
  }),
  p({
    id: "idea-kiyomizu",
    title: "Kiyomizu-dera and Sannenzaka",
    city: "Kyoto",
    region: "Kansai",
    neighborhood: "Higashiyama",
    kind: "Temples",
    tags: ["classic Kyoto", "early start", "lanes"],
    description: "Classic Kyoto, best before the souvenir lanes clog up.",
    whyGo: "Start high and walk downhill.",
    estimatedCostJpy: 2000,
    googleMapsQuery: "Kiyomizu-dera Sannenzaka Kyoto",
    ...wikimedia(
      "Kiyomizu-dera, Kyoto, November 2016 -07.jpg",
      "Kiyomizu-dera temple in Kyoto.",
      "Martin Falbisoner via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Kiyomizu-dera,_Kyoto,_November_2016_-07.jpg",
      "CC BY-SA 4.0",
    ),
    imageSearchQuery: "Kiyomizu-dera Kyoto",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-gion-higashiyama",
    title: "Gion and Higashiyama evening walk",
    city: "Kyoto",
    region: "Kansai",
    neighborhood: "Gion",
    kind: "Neighborhoods",
    tags: ["lanterns", "old streets", "evening"],
    description: "Lanterns, lanes, temple roofs, and the Kyoto everyone pictures.",
    whyGo: "Keep it respectful: private streets and photo rules matter.",
    estimatedCostJpy: 2000,
    googleMapsQuery: "Gion Higashiyama Kyoto evening walk",
    ...fallback("Gion and Higashiyama"),
    imageSearchQuery: "Gion Kyoto evening street",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-arashiyama",
    title: "Arashiyama bamboo, river, and temples",
    city: "Kyoto",
    region: "Kansai",
    neighborhood: "Arashiyama",
    kind: "Day Trips",
    tags: ["bamboo", "river", "temples"],
    description: "Go early for the bamboo, then stay for the river and quieter temple corners.",
    whyGo: "The bamboo is short. Build the day around the whole area.",
    estimatedCostJpy: 3500,
    googleMapsQuery: "Arashiyama Bamboo Grove Kyoto",
    ...wikimedia(
      "Arashiyama Bamboo Grove.jpg",
      "Bamboo grove in Arashiyama, Kyoto.",
      "Mitchwandrew via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Arashiyama_Bamboo_Grove.jpg",
      "CC BY 4.0",
    ),
    imageSearchQuery: "Arashiyama bamboo grove Kyoto",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-nishiki",
    title: "Nishiki Market and Teramachi arcades",
    city: "Kyoto",
    region: "Kansai",
    neighborhood: "Kawaramachi",
    kind: "Food",
    tags: ["market", "rainy day", "shopping"],
    description: "Easy food, small purchases, and covered arcades when the weather turns.",
    whyGo: "Useful on a lighter Kyoto day.",
    estimatedCostJpy: 5000,
    googleMapsQuery: "Nishiki Market Teramachi Kyoto",
    ...fallback("Nishiki Market"),
    imageSearchQuery: "Nishiki Market Kyoto",
    recommendedTime: "midday",
  }),
  p({
    id: "idea-nanzenji-philosopher",
    title: "Nanzen-ji and Philosopher's Path",
    city: "Kyoto",
    region: "Kansai",
    neighborhood: "Sakyo",
    kind: "Temples",
    tags: ["quiet", "walk", "temples"],
    description: "A quieter east-side day with enough room to slow down.",
    whyGo: "Good day to add a rest block if feet are cooked.",
    estimatedCostJpy: 2500,
    googleMapsQuery: "Nanzen-ji Philosopher's Path Kyoto",
    ...fallback("Nanzen-ji and Philosopher's Path"),
    imageSearchQuery: "Nanzen-ji Kyoto Philosopher Path",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-kyoto-tea-crafts",
    title: "Kyoto tea, ceramics, and small craft shops",
    city: "Kyoto",
    region: "Kansai",
    neighborhood: "Kiyomizu / Kawaramachi",
    kind: "Shopping",
    tags: ["tea", "ceramics", "gifts"],
    description: "A flexible shopping idea that feels more Kyoto than another mall.",
    whyGo: "Good for gifts if you want useful, small things.",
    estimatedCostJpy: 6000,
    googleMapsQuery: "Kyoto tea ceramics craft shops",
    ...fallback("Kyoto tea and craft shops"),
    imageSearchQuery: "Kyoto tea ceramics shops",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-dotonbori",
    title: "Dotonbori and Namba food crawl",
    city: "Osaka",
    region: "Kansai",
    neighborhood: "Namba",
    kind: "Food",
    tags: ["street food", "night", "neon"],
    description: "Osaka at full volume. Snack in rounds, not all at once.",
    whyGo: "Come hungry and do not turn dinner into one reservation.",
    estimatedCostJpy: 7500,
    googleMapsQuery: "Dotonbori Namba food Osaka",
    ...wikimedia(
      "Dotonbori, Osaka.jpg",
      "Dotonbori canal and neon signs in Osaka.",
      "Type specimen via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Dotonbori,_Osaka.jpg",
      "CC BY-SA 3.0",
    ),
    imageSearchQuery: "Dotonbori Namba Osaka night",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-shinsekai",
    title: "Shinsekai kushikatsu night",
    city: "Osaka",
    region: "Kansai",
    neighborhood: "Shinsekai",
    kind: "Restaurants",
    tags: ["kushikatsu", "retro", "night"],
    description: "A louder, rougher-feeling Osaka food night than polished malls.",
    whyGo: "Good backup if Dotonbori feels too crowded.",
    estimatedCostJpy: 4500,
    googleMapsQuery: "Shinsekai kushikatsu Osaka",
    ...fallback("Shinsekai kushikatsu"),
    imageSearchQuery: "Shinsekai Osaka kushikatsu",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-kuromon",
    title: "Kuromon Market snack stop",
    city: "Osaka",
    region: "Kansai",
    neighborhood: "Nipponbashi",
    kind: "Food",
    tags: ["market", "snacks", "seafood"],
    description: "An easy snack stop near Namba, best kept casual.",
    whyGo: "Use it as a pass-through, not the whole day.",
    estimatedCostJpy: 3500,
    googleMapsQuery: "Kuromon Market Osaka",
    ...fallback("Kuromon Market"),
    imageSearchQuery: "Kuromon Market Osaka",
    recommendedTime: "midday",
  }),
  p({
    id: "idea-osaka-castle",
    title: "Osaka Castle Park",
    city: "Osaka",
    region: "Kansai",
    neighborhood: "Chuo",
    kind: "Museums",
    tags: ["park", "castle", "lighter day"],
    description: "A park-and-castle day before or after heavier food nights.",
    whyGo: "Exterior and park are often enough.",
    estimatedCostJpy: 2000,
    googleMapsQuery: "Osaka Castle Park Japan",
    ...fallback("Osaka Castle Park"),
    imageSearchQuery: "Osaka Castle Park",
    recommendedTime: "midday",
  }),
  p({
    id: "idea-usj",
    title: "Universal Studios Japan",
    city: "Osaka",
    region: "Kansai",
    neighborhood: "Bay Area",
    kind: "Day Trips",
    tags: ["theme park", "full day", "booking"],
    description: "Big-ticket fun if theme parks are part of your Japan fantasy.",
    whyGo: "Budget jumps fast if Express Pass enters the chat.",
    estimatedCostJpy: 15000,
    googleMapsQuery: "Universal Studios Japan Osaka",
    ...fallback("Universal Studios Japan"),
    imageSearchQuery: "Universal Studios Japan Osaka official",
    recommendedTime: "early morning",
  }),
  p({
    id: "idea-nara-park",
    title: "Nara Park and Todai-ji",
    city: "Nara",
    region: "Kansai",
    neighborhood: "Nara Park",
    kind: "Day Trips",
    tags: ["deer", "temple", "day trip"],
    description: "Easy day trip, giant temple, deer chaos, and a clear change of pace.",
    whyGo: "Go early and keep snacks away from the deer until you are ready.",
    estimatedCostJpy: 4500,
    googleMapsQuery: "Nara Park Todai-ji Japan",
    ...fallback("Nara Park and Todai-ji"),
    imageSearchQuery: "Nara Park Todai-ji deer",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-hiroshima-peace",
    title: "Peace Memorial Park and Museum",
    city: "Hiroshima",
    region: "Chugoku",
    neighborhood: "Peace Park",
    kind: "Museums",
    tags: ["history", "museum", "quiet"],
    description: "Heavy, important, and worth giving proper time.",
    whyGo: "Do this slowly, then keep the evening gentle.",
    estimatedCostJpy: 1000,
    googleMapsQuery: "Hiroshima Peace Memorial Museum Peace Park",
    ...fallback("Hiroshima Peace Memorial Museum"),
    imageSearchQuery: "Hiroshima Peace Memorial Museum",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-atomic-bomb-dome",
    title: "Atomic Bomb Dome riverside walk",
    city: "Hiroshima",
    region: "Chugoku",
    neighborhood: "Peace Park",
    kind: "Museums",
    tags: ["history", "walk", "riverside"],
    description: "Close to the museum, but it should not feel like a pass-by.",
    whyGo: "Pair with Peace Park and leave emotional space.",
    estimatedCostJpy: 500,
    googleMapsQuery: "Atomic Bomb Dome Hiroshima",
    ...fallback("Atomic Bomb Dome"),
    imageSearchQuery: "Atomic Bomb Dome Hiroshima",
    recommendedTime: "afternoon",
  }),
  p({
    id: "idea-hiroshima-okonomiyaki",
    title: "Hiroshima okonomiyaki counter dinner",
    city: "Hiroshima",
    region: "Chugoku",
    neighborhood: "Hondori / Station",
    kind: "Restaurants",
    tags: ["okonomiyaki", "counter", "dinner"],
    description: "Dinner at the counter is the point. Watch the layers get built.",
    whyGo: "A low-effort night after Miyajima or Peace Park.",
    estimatedCostJpy: 3500,
    googleMapsQuery: "Hiroshima okonomiyaki counter restaurant",
    ...fallback("Hiroshima okonomiyaki"),
    imageSearchQuery: "Hiroshima okonomiyaki counter",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-miyajima",
    title: "Miyajima and Itsukushima Shrine",
    city: "Miyajima",
    region: "Chugoku",
    neighborhood: "Miyajima Island",
    kind: "Day Trips",
    tags: ["ferry", "shrine", "water"],
    description: "A ferry day with water, shrine views, deer, and enough walking to feel away.",
    whyGo: "Check tide times if the floating gate photo matters.",
    estimatedCostJpy: 6000,
    googleMapsQuery: "Miyajima Itsukushima Shrine Japan",
    ...wikimedia(
      "Torii and Itsukushima Shrine.jpg",
      "Torii gate and Itsukushima Shrine on Miyajima.",
      "Bgag via Wikimedia Commons",
      "https://commons.wikimedia.org/wiki/File:Torii_and_Itsukushima_Shrine.jpg",
      "CC BY-SA 3.0",
    ),
    imageSearchQuery: "Miyajima Itsukushima Shrine floating torii",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-kenrokuen",
    title: "Kenrokuen and Kanazawa Castle",
    city: "Kanazawa",
    region: "Hokuriku",
    neighborhood: "Kenrokuen",
    kind: "Temples",
    tags: ["garden", "castle", "slow"],
    description: "A refined garden day after the big-city run.",
    whyGo: "Works best before or after peak tour-bus hours.",
    estimatedCostJpy: 2500,
    googleMapsQuery: "Kenrokuen Kanazawa Castle Japan",
    ...fallback("Kenrokuen"),
    imageSearchQuery: "Kenroku-en Kanazawa garden",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-higashi-chaya",
    title: "Higashi Chaya and Omicho Market",
    city: "Kanazawa",
    region: "Hokuriku",
    neighborhood: "Higashi Chaya",
    kind: "Food",
    tags: ["tea houses", "seafood", "gold leaf"],
    description: "Tea houses, seafood bowls, gold leaf sweets, and slow walking.",
    whyGo: "Do market earlier, chaya district later.",
    estimatedCostJpy: 5500,
    googleMapsQuery: "Higashi Chaya Omicho Market Kanazawa",
    ...fallback("Higashi Chaya and Omicho Market"),
    imageSearchQuery: "Higashi Chaya Kanazawa",
    recommendedTime: "midday",
  }),
  p({
    id: "idea-takayama-old-town",
    title: "Takayama old town and morning market",
    city: "Takayama",
    region: "Chubu",
    neighborhood: "Old Town",
    kind: "Day Trips",
    tags: ["old town", "market", "mountain town"],
    description: "Wooden streets, mountain-town pacing, and a softer contrast to Kyoto.",
    whyGo: "Much better if you overnight instead of rushing through.",
    estimatedCostJpy: 4500,
    googleMapsQuery: "Takayama old town morning market Japan",
    ...fallback("Takayama old town"),
    imageSearchQuery: "Takayama old town Japan",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-shirakawa-go",
    title: "Shirakawa-go thatched village",
    city: "Shirakawa-go",
    region: "Chubu",
    neighborhood: "Ogimachi",
    kind: "Day Trips",
    tags: ["village", "countryside", "logistics"],
    description: "Beautiful countryside detour, but it is logistics-heavy.",
    whyGo: "Reserve buses if travelling at busy times.",
    estimatedCostJpy: 8000,
    googleMapsQuery: "Shirakawa-go Ogimachi Japan",
    ...fallback("Shirakawa-go"),
    imageSearchQuery: "Shirakawa-go thatched village",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-sapporo",
    title: "Sapporo ramen, Odori Park, and Susukino",
    city: "Hokkaido",
    region: "Hokkaido",
    neighborhood: "Sapporo",
    kind: "Branch Ideas",
    tags: ["ramen", "cooler weather", "night"],
    description: "Cooler air, easy food, and a clean landing after a long transfer.",
    whyGo: "Good northern branch if September heat sounds exhausting.",
    estimatedCostJpy: 5500,
    googleMapsQuery: "Sapporo ramen Odori Park Susukino",
    ...fallback("Sapporo"),
    imageSearchQuery: "Sapporo Odori Park",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-otaru",
    title: "Otaru canal and sushi day",
    city: "Hokkaido",
    region: "Hokkaido",
    neighborhood: "Otaru",
    kind: "Branch Ideas",
    tags: ["canal", "sushi", "day trip"],
    description: "Canal walks, glass shops, sushi, and a gentle day by the water.",
    whyGo: "An easy Hokkaido day trip from Sapporo.",
    estimatedCostJpy: 6500,
    googleMapsQuery: "Otaru Canal sushi Hokkaido",
    ...fallback("Otaru"),
    imageSearchQuery: "Otaru canal Hokkaido",
    recommendedTime: "morning",
  }),
  p({
    id: "idea-fukuoka-yatai",
    title: "Fukuoka yatai and Hakata ramen",
    city: "Kyushu",
    region: "Kyushu",
    neighborhood: "Fukuoka",
    kind: "Branch Ideas",
    tags: ["ramen", "yatai", "night food"],
    description: "A food-first southern branch with easier nights and a different rhythm.",
    whyGo: "Yatai are weather-dependent, so keep a backup.",
    estimatedCostJpy: 7000,
    googleMapsQuery: "Fukuoka yatai Hakata ramen",
    ...fallback("Fukuoka yatai"),
    imageSearchQuery: "Fukuoka yatai Hakata",
    recommendedTime: "evening",
  }),
  p({
    id: "idea-beppu-yufuin",
    title: "Beppu or Yufuin onsen town",
    city: "Kyushu",
    region: "Kyushu",
    neighborhood: "Beppu / Yufuin",
    kind: "Branch Ideas",
    tags: ["onsen", "steam", "overnight"],
    description: "Steam, baths, mountain views, and a slower southern reset.",
    whyGo: "Choose one unless you add an overnight.",
    estimatedCostJpy: 13000,
    googleMapsQuery: "Beppu Yufuin onsen Kyushu Japan",
    ...fallback("Beppu or Yufuin"),
    imageSearchQuery: "Beppu Yufuin onsen Japan",
    recommendedTime: "morning",
  }),
];
