import type { RouteSuggestion, Trip, TripActivity, TripAttachment, TripFlight, TripHotel } from "./tripTypes";

const tripId = "peru-2026" as const;

const scenic = (name: string) =>
  `linear-gradient(135deg, hsl(${Math.abs([...name].reduce((sum, char) => sum + char.charCodeAt(0), 0)) % 360} 48% 86%) 0%, #f7efe0 52%, #dceee7 100%)`;

const activity = (
  id: string,
  day: number,
  date: string,
  city: string,
  title: string,
  description: string,
  category: TripActivity["category"],
  address: string,
  latitude: number | undefined,
  longitude: number | undefined,
  options: Partial<TripActivity> = {},
): TripActivity => ({
  id,
  tripId,
  day,
  date,
  city,
  country: "Peru",
  title,
  description,
  category,
  address,
  googleMapsQuery: options.googleMapsQuery ?? `${title}, ${address || city}, Peru`,
  latitude,
  longitude,
  startTime: options.startTime,
  endTime: options.endTime,
  duration: options.duration ?? "1-2 hr",
  travelTimeFromPrevious: options.travelTimeFromPrevious ?? "",
  transportMode: options.transportMode ?? "",
  estimatedCost: options.estimatedCost ?? 0,
  currency: options.currency ?? "CAD",
  bookingReference: options.bookingReference ?? "",
  flightInfo: options.flightInfo,
  hotelInfo: options.hotelInfo,
  attachmentIds: options.attachmentIds ?? [],
  notes: options.notes ?? "",
  imageUrl: options.imageUrl ?? "",
  imageAlt: options.imageAlt ?? `Scenic placeholder for ${title}.`,
  priority: options.priority ?? 3,
  isBooked: options.isBooked ?? false,
  isCompleted: options.isCompleted ?? false,
  source: "wanderlog",
});

export const peruFlights: TripFlight[] = [
  {
    id: "peru-flight-ac1810",
    tripId,
    airline: "Air Canada",
    flightNumber: "AC1810",
    departureAirport: "Toronto Pearson International Airport (YYZ)",
    arrivalAirport: "Cancun International Airport (CUN)",
    departureTime: "2026-07-11T07:15:00-04:00",
    arrivalTime: "2026-07-11T10:15:00-05:00",
    status: "manual / not live yet",
    notes: "Outbound connection through Cancun. Status is manual until a flight API is connected.",
  },
  {
    id: "peru-flight-la2459",
    tripId,
    airline: "LATAM",
    flightNumber: "LA2459",
    departureAirport: "Cancun International Airport (CUN)",
    arrivalAirport: "Jorge Chavez International Airport (LIM)",
    departureTime: "2026-07-11T15:25:00-05:00",
    arrivalTime: "2026-07-11T20:40:00-05:00",
    status: "manual / not live yet",
    notes: "Long layover cushion. Keep Lima to Cusco timing visible in the tracker.",
  },
  {
    id: "peru-flight-la2454",
    tripId,
    airline: "LATAM",
    flightNumber: "LA2454",
    departureAirport: "Jorge Chavez International Airport (LIM)",
    arrivalAirport: "Cancun International Airport (CUN)",
    departureTime: "2026-07-26T10:45:00-05:00",
    arrivalTime: "2026-07-26T16:15:00-05:00",
    status: "manual / not live yet",
    notes: "Return connection starts in Lima.",
  },
  {
    id: "peru-flight-ws2131",
    tripId,
    airline: "WestJet",
    flightNumber: "WS2131",
    departureAirport: "Cancun International Airport (CUN)",
    arrivalAirport: "Toronto Pearson International Airport (YYZ)",
    departureTime: "2026-07-26T19:40:00-05:00",
    arrivalTime: "2026-07-27T00:40:00-04:00",
    status: "manual / not live yet",
    notes: "Overnight arrival back in Toronto.",
  },
];

export const peruHotels: TripHotel[] = [
  {
    id: "hotel-samay-wasi",
    tripId,
    name: "Samay Wasi Youth Hostels Cusco",
    city: "Cusco",
    country: "Peru",
    address: "Atoqsayk'uchi 416, Cusco 08003, Peru",
    checkIn: "2026-07-11",
    checkOut: "2026-07-14",
    estimatedCost: 75.88,
    currency: "CAD",
    latitude: -13.512909,
    longitude: -71.975335,
    notes: "Cusco base before Sacred Valley and Machu Picchu.",
  },
  {
    id: "hotel-casa-inka",
    tripId,
    name: "Casa Inka B&B",
    city: "Ollantaytambo",
    country: "Peru",
    address: "Ollantaytambo, Peru",
    checkIn: "2026-07-14",
    checkOut: "2026-07-15",
    estimatedCost: 45,
    currency: "CAD",
    notes: "Useful overnight before the train.",
  },
  {
    id: "hotel-inkas-land",
    tripId,
    name: "Hotel INKA'S LAND",
    city: "Aguas Calientes",
    country: "Peru",
    address: "Aguas Calientes, Peru",
    checkIn: "2026-07-15",
    checkOut: "2026-07-16",
    estimatedCost: 53.46,
    currency: "CAD",
    notes: "Sleep near the Machu Picchu buses.",
  },
  {
    id: "hotel-friendly-aqp",
    tripId,
    name: "Hotel Friendly AQP",
    city: "Arequipa",
    country: "Peru",
    address: "Ca. Consuelo 418, Arequipa 04001, Peru",
    checkIn: "2026-07-19",
    checkOut: "2026-07-23",
    estimatedCost: 136.8,
    currency: "CAD",
    latitude: -16.400574,
    longitude: -71.540447,
    notes: "Arequipa base around Colca Canyon.",
  },
  {
    id: "hotel-los-portales-chivay",
    tripId,
    name: "HOTEL LOS PORTALES DE CHIVAY",
    city: "Chivay",
    country: "Peru",
    address: "Arequipa 603, Chivay, Peru",
    checkIn: "2026-07-20",
    checkOut: "2026-07-21",
    estimatedCost: 56,
    currency: "CAD",
    latitude: -15.639689,
    longitude: -71.601256,
    notes: "Overnight for the canyon route.",
  },
  {
    id: "hotel-paracas-backpacker",
    tripId,
    name: "Paracas Backpacker's House",
    city: "Paracas",
    country: "Peru",
    address: "Playa, Paracas, Peru",
    checkIn: "2026-07-23",
    checkOut: "2026-07-24",
    estimatedCost: 31.09,
    currency: "CAD",
    latitude: -13.834177,
    longitude: -76.248447,
    notes: "Close enough for the Ballestas morning.",
  },
  {
    id: "hotel-wild-rover",
    tripId,
    name: "Wild Rover Huacachina",
    city: "Huacachina",
    country: "Peru",
    address: "Av. Angela de Perotti S/N Balneario de, Huacachina, Peru",
    checkIn: "2026-07-24",
    checkOut: "2026-07-25",
    estimatedCost: 78.36,
    currency: "CAD",
    latitude: -14.086532,
    longitude: -75.762849,
    notes: "Desert night after sandboarding.",
  },
  {
    id: "hotel-alpes-lima",
    tripId,
    name: "Alpes Lima Kennedy Park",
    city: "Lima",
    country: "Peru",
    address: "Miraflores, Lima, Peru",
    checkIn: "2026-07-25",
    checkOut: "2026-07-26",
    estimatedCost: 66.83,
    currency: "CAD",
    notes: "Final Lima buffer before the flight home.",
  },
];

export const peruAttachments: TripAttachment[] = [
  {
    id: "peru-flight-confirmations",
    tripId,
    fileName: "flight-confirmations-placeholder.pdf",
    type: "booking",
    note: "Metadata placeholder only. Do not store private tickets here yet.",
    localReference: "Paste booking reference or future secure file link here.",
    isSensitivePlaceholder: true,
  },
  {
    id: "peru-machu-ticket",
    tripId,
    activityId: "peru-machu-picchu",
    fileName: "machu-picchu-ticket-placeholder.pdf",
    type: "ticket",
    note: "Attach or link the real ticket later in a secure storage layer.",
    isSensitivePlaceholder: true,
  },
  {
    id: "peru-hotel-confirmations",
    tripId,
    fileName: "hotel-confirmations-placeholder.pdf",
    type: "booking",
    note: "Local-only planning record for hotel confirmations.",
    isSensitivePlaceholder: true,
  },
  {
    id: "peru-wanderlog-export",
    tripId,
    fileName: "wanderlog-import-notes.md",
    type: "note",
    note: "Use the import template to paste fuller Wanderlog or Google Doc notes.",
  },
  {
    id: "peru-passport-visa-placeholder",
    tripId,
    fileName: "passport-visa-notes-placeholder.txt",
    type: "note",
    note: "Non-sensitive reminder only. Do not store passport scans or private IDs in localStorage.",
    isSensitivePlaceholder: true,
  },
];

export const peruActivities: TripActivity[] = [
  activity("peru-yyz-outbound", 1, "2026-07-11", "Toronto", "Toronto Pearson departure", "The trip starts with a long airport day. Keep snacks and chargers easy to reach.", "Flight", "6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada", 43.679835, -79.628383, { estimatedCost: 1813.82, duration: "3 hr airport buffer", transportMode: "flight", flightInfo: peruFlights[0], attachmentIds: ["peru-flight-confirmations"], isBooked: true, priority: 1 }),
  activity("peru-cancun-connection", 1, "2026-07-11", "Cancun", "Cancun connection", "A connection day, not a sightseeing day. The win is making the next flight calmly.", "Flight", "Carr. a Aeropuerto Cancun, 77500 Cancun, Q.R., Mexico", 21.041923, -86.874384, { duration: "5 hr layover", transportMode: "flight", flightInfo: peruFlights[1], isBooked: true, priority: 2 }),
  activity("peru-lima-arrival", 1, "2026-07-11", "Lima", "Lima airport arrival", "Land, reset, and keep the Cusco transfer simple.", "Transit", "Avenida Morales Duarez s/n, Callao, Peru", -12.029701, -77.116228, { duration: "1-2 hr", transportMode: "airport", priority: 2 }),
  activity("peru-cusco-arrival", 1, "2026-07-11", "Cusco", "Cusco arrival", "High altitude starts here. Do less than you think on the first night.", "Transit", "Av. Velasco Astete, Cusco 08006, Peru", -13.538202, -71.94377, { duration: "45 min", transportMode: "flight", priority: 1 }),
  activity("peru-samay-wasi", 1, "2026-07-11", "Cusco", "Samay Wasi check-in", "Get settled and leave the first night quiet.", "Hotel", "Atoqsayk'uchi 416, Cusco 08003, Peru", -13.512909, -71.975335, { duration: "30 min", hotelInfo: peruHotels[0], attachmentIds: ["peru-hotel-confirmations"], estimatedCost: 75.88, isBooked: true, priority: 1 }),

  activity("peru-qorikancha", 2, "2026-07-12", "Cusco", "Qorikancha", "A strong first Cusco stop: Inca stonework, colonial layers, and no need to rush.", "Must See", "Santo Domingo s/n, Cusco 08000, Peru", -13.520237, -71.975234, { duration: "1 hr", travelTimeFromPrevious: "10-15 min from San Blas", priority: 1 }),
  activity("peru-saqsaywaman", 2, "2026-07-12", "Cusco", "Saqsaywaman", "Big stones, big views, and a good way to feel Cusco's scale.", "Must See", "Cusco 08002, Peru", -13.509856, -71.981688, { duration: "1.5-2 hr", travelTimeFromPrevious: "15 min drive or steep walk", priority: 1 }),
  activity("peru-qenqo", 2, "2026-07-12", "Cusco", "Q'enqo Archaeological Complex", "Pair it with Saqsaywaman while you are already above the city.", "Nice To Have", "F2RH+CPX, Cusco 08003, Peru", -13.508898, -71.970656, { duration: "45 min", travelTimeFromPrevious: "10 min drive", priority: 3 }),

  activity("peru-pisac", 3, "2026-07-13", "Pisac", "Pisac Archaeological Park", "Sacred Valley starts properly here. Go for terraces, views, and a slower mountain day.", "Must See", "H5R4+X8X, Pisac 08105, Peru", -13.407523, -71.844154, { duration: "2-3 hr", travelTimeFromPrevious: "1 hr from Cusco", transportMode: "car", priority: 1 }),
  activity("peru-awana-kancha", 3, "2026-07-13", "Pisac", "Awana Kancha", "Easy add-on for textiles and alpacas without making the day too heavy.", "Nice To Have", "km 23, a, Pisac, Cusco, Peru", -13.466413, -71.890914, { duration: "45-60 min", travelTimeFromPrevious: "25 min", priority: 3 }),

  activity("peru-moray", 4, "2026-07-14", "Maras", "Moray", "Those circular terraces are stranger and better in person.", "Must See", "Maras 08655, Peru", -13.329857, -72.197144, { duration: "1 hr", travelTimeFromPrevious: "1.5 hr from Cusco", transportMode: "car", priority: 1 }),
  activity("peru-maras", 4, "2026-07-14", "Maras", "Maras salt mines", "Worth the detour for the landscape alone.", "Must See", "Maras 08656, Peru", -13.335562, -72.15701, { duration: "1 hr", travelTimeFromPrevious: "20 min", priority: 1 }),
  activity("peru-ollantaytambo-ruins", 4, "2026-07-14", "Ollantaytambo", "Ollantaytambo Archaeological Site", "A good final Sacred Valley climb before the train leg.", "Must See", "PPVM+6J7, Ollantaytambo 08676, Peru", -13.256966, -72.26594, { duration: "1.5 hr", travelTimeFromPrevious: "1 hr from Maras", priority: 1 }),
  activity("peru-inca-rail-out", 4, "2026-07-14", "Ollantaytambo", "Inca Rail to Aguas Calientes", "This is the rail moment. Keep the afternoon loose so the train is not stressful.", "Transit", "PPPJ+Q9P, Ollantaytambo 08675, Peru", -13.263044, -72.269056, { startTime: "16:26", duration: "1.5 hr", transportMode: "train", isBooked: true, priority: 1 }),
  activity("peru-aguas-calientes", 4, "2026-07-14", "Aguas Calientes", "Aguas Calientes arrival", "Sleep close to the Machu Picchu buses. That is the point of this stop.", "Hotel", "Aguas Calientes 08681, Peru", -13.154706, -72.525441, { duration: "30 min", hotelInfo: peruHotels[2], attachmentIds: ["peru-hotel-confirmations"], isBooked: true, priority: 1 }),

  activity("peru-machu-picchu", 5, "2026-07-15", "Aguas Calientes", "Machu Picchu", "The headline day. Go early, keep expectations simple, and let the place do the work.", "Non-Negotiable", "Historic Sanctuary of Machu Picchu, 08680, Peru", -13.163199, -72.545262, { duration: "3-4 hr", estimatedCost: 132.3, attachmentIds: ["peru-machu-ticket"], isBooked: true, priority: 1 }),
  activity("peru-inca-rail-return", 5, "2026-07-15", "Aguas Calientes", "Train back from Machu Picchu", "Build the day around the return time. This is not the day to improvise wildly.", "Transit", "Estacion de ferrocarril S/N, Aguas Calientes 08681, Peru", -13.155633, -72.524544, { startTime: "14:20", duration: "1.5 hr", transportMode: "train", isBooked: true, priority: 1 }),
  activity("peru-ollantaytambo-return", 5, "2026-07-15", "Ollantaytambo", "Ollantaytambo transfer", "Transfer point back toward Cusco.", "Transit", "Ollantaytambo, Peru", -13.258369, -72.264268, { duration: "30 min", travelTimeFromPrevious: "train arrival", priority: 2 }),
  activity("peru-cusco-return", 5, "2026-07-15", "Cusco", "Cusco return", "Back to the city after the big day. Keep dinner easy.", "Transit", "Cusco, Peru", -13.53195, -71.967463, { duration: "2 hr", transportMode: "car or train connection", priority: 2 }),

  activity("peru-vinicunca", 6, "2026-07-16", "Cusco", "Vinicunca Rainbow Mountain", "Beautiful if the weather is kind, but this is a heavy altitude day.", "Non-Negotiable", "Vinicunca, 08225, Peru", -13.870166, -71.30299, { duration: "Full day", travelTimeFromPrevious: "3 hr each way", transportMode: "tour van + hike", estimatedCost: 239, priority: 1, notes: "Make this optional if altitude recovery is rough." }),

  activity("peru-san-blas", 7, "2026-07-17", "Cusco", "Plaza San Blas", "A calmer Cusco day: coffee, wandering, and streets that make you slow down.", "Nice To Have", "F2MG+W7Q Cuesta de San Blas, Cusco 08003, Peru", -13.515163, -71.974253, { duration: "1-2 hr", priority: 3 }),
  activity("peru-san-pedro-market", 7, "2026-07-17", "Cusco", "San Pedro Market", "Go for fruit, snacks, and a normal city rhythm after the tour days.", "Must See", "Thupaq Amaru 477, Cusco 08002, Peru", -13.520958, -71.982668, { duration: "1 hr", priority: 2 }),

  activity("peru-ausangate", 8, "2026-07-18", "Cusco", "Ausangate 7 Lagunas", "Another mountain day. Worth it if energy is good, easy to cut if you need rest.", "Extra", "Nevado Auzangate Cusco, 08000, Peru", -13.758216, -71.218782, { duration: "Full day", travelTimeFromPrevious: "3 hr each way", transportMode: "tour van + hike", estimatedCost: 81.08, priority: 4 }),

  activity("peru-cusco-airport", 9, "2026-07-19", "Cusco", "Cusco airport", "Transit day into the south. Keep the morning boring on purpose.", "Flight", "Av. Velasco Astete, Cusco 08006, Peru", -13.538202, -71.94377, { duration: "2 hr airport buffer", transportMode: "flight", priority: 1 }),
  activity("peru-arequipa-airport", 9, "2026-07-19", "Arequipa", "Arequipa arrival", "New city, lower pace. The white-stone center is the reward.", "Flight", "Av. Aeropuerto S/N, Cerro Colorado 04017, Peru", -16.344557, -71.568187, { duration: "1 hr", transportMode: "flight", priority: 1 }),
  activity("peru-santa-catalina", 9, "2026-07-19", "Arequipa", "Santa Catalina Monastery", "Do this when you have time to wander. It is more like a small city than one stop.", "Must See", "Santa Catalina 301, Arequipa 04001, Peru", -16.396109, -71.536577, { duration: "1.5-2 hr", priority: 1 }),
  activity("peru-friendly-checkin", 9, "2026-07-19", "Arequipa", "Hotel Friendly AQP check-in", "Settle in before the canyon route.", "Hotel", "Ca. Consuelo 418, Arequipa 04001, Peru", -16.400574, -71.540447, { duration: "30 min", hotelInfo: peruHotels[3], isBooked: true, attachmentIds: ["peru-hotel-confirmations"], priority: 1 }),

  activity("peru-colca-private", 10, "2026-07-20", "Arequipa", "Colca Canyon private transport", "A long transfer day, but it gets the canyon into the trip cleanly.", "Transit", "Arequipa 04501, Peru", -16.387349, -71.524043, { duration: "4-5 hr", transportMode: "private transport", estimatedCost: 113.8, priority: 1 }),
  activity("peru-chivay", 10, "2026-07-20", "Chivay", "Chivay", "A practical overnight, not a checklist stop.", "Nice To Have", "Chivay, Peru", -15.638845, -71.602044, { duration: "Evening", priority: 2 }),
  activity("peru-los-portales", 10, "2026-07-20", "Chivay", "Los Portales de Chivay check-in", "Sleep near the canyon route so the morning is easier.", "Hotel", "Arequipa 603, Chivay, Peru", -15.639689, -71.601256, { duration: "30 min", hotelInfo: peruHotels[4], estimatedCost: 56, isBooked: true, attachmentIds: ["peru-hotel-confirmations"], priority: 1 }),

  activity("peru-condor-viewpoint", 11, "2026-07-21", "Colca Canyon", "Mirador Cruz del Condor", "Go early. The canyon and condors are the reason for the overnight.", "Must See", "Mirador Cruz del Condor, Peru", -15.611288, -71.906097, { duration: "1 hr", travelTimeFromPrevious: "1.5 hr from Chivay", priority: 1 }),
  activity("peru-ruta-sillar", 11, "2026-07-21", "Arequipa", "Ruta del Sillar", "Good if you still have energy after the canyon return.", "Nice To Have", "J9RV+495 Canteras Anashuayco, Cerro Colorado 04017, Peru", -16.359736, -71.6065, { duration: "1-2 hr", priority: 3 }),
  activity("peru-arequipa-food", 11, "2026-07-21", "Arequipa", "Arequipa food crawl", "La Nueva Palomino, queso helado, and a relaxed plaza evening.", "Food", "Plaza de Armas, Arequipa 04001, Peru", -16.398858, -71.536917, { duration: "2-3 hr", estimatedCost: 45, priority: 2 }),

  activity("peru-mundo-alpaca", 12, "2026-07-22", "Arequipa", "Mundo Alpaca", "Light, easy, and useful if you want textiles without a big detour.", "Nice To Have", "Alameda San Lazaro 101, Arequipa 04001, Peru", -16.392923, -71.535454, { duration: "45 min", priority: 3 }),
  activity("peru-santuarios-andinos", 12, "2026-07-22", "Arequipa", "Museo Santuarios Andinos", "A short museum stop with real weight. Keep the rest of the day gentle.", "Nice To Have", "C. la Merced 110, Arequipa 04001, Peru", -16.399961, -71.537755, { duration: "1 hr", priority: 3 }),

  activity("peru-arequipa-depart", 13, "2026-07-23", "Arequipa", "Arequipa airport", "Travel day to the coast. Pack this day lightly.", "Flight", "Av. Aeropuerto S/N, Cerro Colorado 04017, Peru", -16.344557, -71.568187, { duration: "2 hr airport buffer", transportMode: "flight", priority: 1 }),
  activity("peru-lima-transfer", 13, "2026-07-23", "Lima", "Lima airport transfer", "Connection point before Paracas.", "Transit", "Avenida Morales Duarez s/n, Callao, Peru", -12.029701, -77.116228, { duration: "1 hr", transportMode: "flight", priority: 2 }),
  activity("peru-paracas", 13, "2026-07-23", "Paracas", "Paracas arrival", "Coast reset after the altitude and canyon days.", "Hotel", "Paracas 11550, Peru", -13.83317, -76.247786, { duration: "Evening", travelTimeFromPrevious: "3.5-4 hr from Lima", hotelInfo: peruHotels[5], isBooked: true, attachmentIds: ["peru-hotel-confirmations"], priority: 1 }),

  activity("peru-ballestas", 14, "2026-07-24", "Paracas", "Islas Ballestas", "Morning boat, wildlife, sea air. Weather can decide the mood.", "Must See", "Islas Ballestas, Peru", -13.731831, -76.39773, { duration: "2 hr", estimatedCost: 56.9, priority: 1 }),
  activity("peru-huacachina-oasis", 14, "2026-07-24", "Huacachina", "Huacachina Oasis", "A sharp change of scene: dunes, heat, and one weird little lagoon.", "Must See", "Huacachina 11000, Peru", -14.087352, -75.763106, { duration: "1 hr", travelTimeFromPrevious: "1.5 hr from Paracas", priority: 1 }),
  activity("peru-sandboard", 14, "2026-07-24", "Huacachina", "Huacachina sandboarding", "Do it for the dunes and sunset, not because it is subtle.", "Nice To Have", "Av. Angela Perotti, Ica 11000, Peru", -14.088556, -75.762408, { duration: "2 hr", estimatedCost: 142.26, priority: 2 }),
  activity("peru-wild-rover", 14, "2026-07-24", "Huacachina", "Wild Rover Huacachina check-in", "Simple overnight after the desert day.", "Hotel", "Av. Angela de Perotti S/N Balneario de, Huacachina, Peru", -14.086532, -75.762849, { duration: "30 min", hotelInfo: peruHotels[6], estimatedCost: 78.36, isBooked: true, attachmentIds: ["peru-hotel-confirmations"], priority: 1 }),

  activity("peru-lima", 15, "2026-07-25", "Lima", "Lima buffer day", "Keep this flexible. Good food, a walk, and no heroic scheduling before flying home.", "Nice To Have", "Lima, Peru", -12.046689, -77.043089, { duration: "Half day", travelTimeFromPrevious: "4-5 hr from Huacachina", estimatedCost: 80, hotelInfo: peruHotels[7], priority: 2 }),

  activity("peru-lima-depart", 16, "2026-07-26", "Lima", "Lima airport departure", "Final airport day. Leave extra time and make this boring in the best way.", "Flight", "Avenida Morales Duarez s/n, Callao, Peru", -12.029701, -77.116228, { duration: "3 hr airport buffer", transportMode: "flight", flightInfo: peruFlights[2], attachmentIds: ["peru-flight-confirmations"], isBooked: true, priority: 1 }),
  activity("peru-cancun-return", 16, "2026-07-26", "Cancun", "Cancun return connection", "The last connection before home.", "Flight", "Carr. a Aeropuerto Cancun, 77500 Cancun, Q.R., Mexico", 21.041923, -86.874384, { duration: "3 hr layover", transportMode: "flight", flightInfo: peruFlights[3], isBooked: true, priority: 1 }),
  activity("peru-toronto-return", 16, "2026-07-26", "Toronto", "Toronto arrival", "Home stretch. Arrival is just after midnight on July 27.", "Flight", "6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada", 43.679835, -79.628383, { duration: "Arrival", transportMode: "flight", isBooked: true, priority: 1 }),
].map((item) => ({
  ...item,
  imageUrl: item.imageUrl || scenic(item.title),
}));

export const peruRouteSuggestions: RouteSuggestion[] = [
  {
    id: "peru-altitude-warning",
    tripId,
    severity: "warning",
    day: 1,
    city: "Cusco",
    title: "Treat the first Cusco night as recovery",
    detail: "The plan lands at altitude after a long flight chain. Keep day 1 quiet and avoid stacking paid plans that night.",
  },
  {
    id: "peru-mountain-days",
    tripId,
    severity: "warning",
    day: 6,
    city: "Cusco",
    title: "Two heavy mountain days are close together",
    detail: "Vinicunca and Ausangate are both full altitude days. Keep Ausangate optional unless recovery feels good.",
  },
  {
    id: "peru-coast-transfer",
    tripId,
    severity: "info",
    day: 13,
    city: "Paracas",
    title: "Coast leg is a routing day",
    detail: "Arequipa to Lima to Paracas is mostly movement. Avoid adding much beyond check-in and food.",
  },
];

export const peruTrip: Trip = {
  id: tripId,
  title: "Peru Trip",
  country: "Peru",
  startDate: "2026-07-11",
  endDate: "2026-07-26",
  currency: "CAD",
  description: "A July 2026 Peru route through Cusco, the Sacred Valley, Machu Picchu, Arequipa, Colca Canyon, Paracas, Huacachina, and Lima.",
  activities: peruActivities,
  flights: peruFlights,
  hotels: peruHotels,
  attachments: peruAttachments,
  notes: "Seeded from the public Wanderlog plan. The Google Doc can be imported later if access is granted or content is pasted.",
};
