import type { RouteSuggestion, Trip, TripActivity, TripAttachment, TripFlight, TripHotel } from "./tripTypes";

export const PERU_CAD_TO_PEN = 2.5;
export const PERU_WANDERLOG_URL = "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru";
export const PERU_GOOGLE_DOC_URL = "https://docs.google.com/document/d/1huAZVsFsUmAh80jzrkG6IzBke6sNUKhoJp3wjIOjJfI/edit?tab=t.ydmxzx6uluaw";

const scenic = (name: string) =>
  `linear-gradient(135deg, hsl(${Math.abs([...name].reduce((sum, char) => sum + char.charCodeAt(0), 0)) % 360} 48% 86%) 0%, #f7efe0 52%, #dceee7 100%)`;

export const peruActivities: TripActivity[] = [
  {
    "id": "peru-wanderlog-142351656",
    "tripId": "peru-2026",
    "day": 1,
    "date": "2026-07-11",
    "city": "Toronto",
    "region": "Flight connection",
    "country": "Canada",
    "title": "Toronto Pearson International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada",
    "googleMapsQuery": "Toronto Pearson International Airport, 6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada",
    "latitude": 43.6798345,
    "longitude": -79.62838339999999,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 4534.55,
    "currency": "PEN",
    "costLocal": 4534.55,
    "localCurrencyCode": "PEN",
    "costCad": 1813.82,
    "costCategory": "flight",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Toronto Pearson International Airport.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "142351656",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-169020384",
    "tripId": "peru-2026",
    "day": 1,
    "date": "2026-07-11",
    "city": "Cancun",
    "region": "Flight connection",
    "country": "Mexico",
    "title": "Cancun International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Carr. a Aeropuerto Cancún, 77500 Cancún, Q.R., Mexico",
    "googleMapsQuery": "Cancun International Airport, Carr. a Aeropuerto Cancún, 77500 Cancún, Q.R., Mexico",
    "latitude": 21.0419232,
    "longitude": -86.8743844,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Airport transfer, confirm timing",
    "transportMode": "flight/airport",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Cancun International Airport.",
    "priority": 2,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "169020384",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Exact route time missing from Wanderlog",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Airport transfer, confirm timing",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-607451114",
    "tripId": "peru-2026",
    "day": 1,
    "date": "2026-07-11",
    "city": "Lima",
    "region": "Lima",
    "country": "Peru",
    "title": "New Jorge Chávez International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Avenida Morales Duárez s/n, Callao, Peru",
    "googleMapsQuery": "New Jorge Chávez International Airport, Avenida Morales Duárez s/n, Callao, Peru",
    "latitude": -12.029701099999999,
    "longitude": -77.11622779999999,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Airport transfer, confirm timing",
    "transportMode": "flight/airport",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for New Jorge Chávez International Airport.",
    "priority": 3,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "607451114",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Exact route time missing from Wanderlog",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Airport transfer, confirm timing",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-565557133",
    "tripId": "peru-2026",
    "day": 1,
    "date": "2026-07-11",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Alejandro Velasco Astete International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Av. Velasco Astete, Cusco 08006, Peru",
    "googleMapsQuery": "Alejandro Velasco Astete International Airport, Av. Velasco Astete, Cusco 08006, Peru",
    "latitude": -13.538201899999999,
    "longitude": -71.94376989999999,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Airport transfer, confirm timing",
    "transportMode": "flight/airport",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Alejandro Velasco Astete International Airport.",
    "priority": 4,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "565557133",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Exact route time missing from Wanderlog",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Airport transfer, confirm timing",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-593696038",
    "tripId": "peru-2026",
    "day": 1,
    "date": "2026-07-11",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Samay Wasi Youth Hostels Cusco",
    "type": "hotel",
    "description": "Lodging stop imported from the public Peru plan.",
    "category": "Hotel",
    "address": "Atoqsayk'uchi 416, Cusco 08003, Peru",
    "googleMapsQuery": "Samay Wasi Youth Hostels Cusco, Atoqsayk'uchi 416, Cusco 08003, Peru",
    "latitude": -13.512908999999999,
    "longitude": -71.9753348,
    "startTime": "",
    "endTime": "",
    "duration": "Check-in / stay",
    "travelTimeFromPrevious": "15-30 min local ride",
    "transportMode": "taxi/local transit",
    "estimatedCost": 189.7,
    "currency": "PEN",
    "costLocal": 189.7,
    "localCurrencyCode": "PEN",
    "costCad": 75.88,
    "costCategory": "hotel",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Samay Wasi Youth Hostels Cusco.",
    "priority": 5,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "593696038",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "15-30 min local ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-937423377",
    "tripId": "peru-2026",
    "day": 2,
    "date": "2026-07-12",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Qorikancha",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Santo Domingo s/n, Cusco 08000, Peru",
    "googleMapsQuery": "Qorikancha, Santo Domingo s/n, Cusco 08000, Peru",
    "latitude": -13.5202365,
    "longitude": -71.97523389999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Qorikancha.",
    "priority": 1,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "937423377",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-433041121",
    "tripId": "peru-2026",
    "day": 2,
    "date": "2026-07-12",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Saqsaywaman",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "Cusco 08002, Peru",
    "googleMapsQuery": "Saqsaywaman, Cusco 08002, Peru",
    "latitude": -13.509856,
    "longitude": -71.9816878,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Saqsaywaman.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "433041121",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-316686917",
    "tripId": "peru-2026",
    "day": 2,
    "date": "2026-07-12",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Q'enco Archaeological Complex",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "F2RH+CPX, Cusco 08003, Peru",
    "googleMapsQuery": "Q'enco Archaeological Complex, F2RH+CPX, Cusco 08003, Peru",
    "latitude": -13.5088984,
    "longitude": -71.9706558,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Q'enco Archaeological Complex.",
    "priority": 3,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "316686917",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-998485771",
    "tripId": "peru-2026",
    "day": 3,
    "date": "2026-07-13",
    "city": "Pisac",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Parque Arqueológico Pisac",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "H5R4+X8X, Písac 08105, Peru",
    "googleMapsQuery": "Parque Arqueológico Pisac, H5R4+X8X, Písac 08105, Peru",
    "latitude": -13.407523399999999,
    "longitude": -71.84415419999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Parque Arqueológico Pisac.",
    "priority": 1,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "998485771",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-843498859",
    "tripId": "peru-2026",
    "day": 3,
    "date": "2026-07-13",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Awana Kancha",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "km 23, a, Pisac, Cusco, Peru",
    "googleMapsQuery": "Awana Kancha, km 23, a, Pisac, Cusco, Peru",
    "latitude": -13.466413099999999,
    "longitude": -71.89091379999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "30-60 min drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Awana Kancha.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "843498859",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "30-60 min drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-904717410",
    "tripId": "peru-2026",
    "day": 4,
    "date": "2026-07-14",
    "city": "Maras",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Zona Arqueologica Moray",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "Maras 08655, Peru",
    "googleMapsQuery": "Zona Arqueologica Moray, Maras 08655, Peru",
    "latitude": -13.3298569,
    "longitude": -72.19714379999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Zona Arqueologica Moray.",
    "priority": 1,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "904717410",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-664935588",
    "tripId": "peru-2026",
    "day": 4,
    "date": "2026-07-14",
    "city": "Maras",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Maras",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "08656, Peru",
    "googleMapsQuery": "Maras, 08656, Peru",
    "latitude": -13.3355616,
    "longitude": -72.1570098,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "15-30 min local ride",
    "transportMode": "taxi/local transit",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Maras.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "664935588",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "15-30 min local ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-552571440",
    "tripId": "peru-2026",
    "day": 4,
    "date": "2026-07-14",
    "city": "Ollantaytambo",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Ollantaytambo Archeological Site",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "PPVM+6J7, Ollantaytambo 08676, Peru",
    "googleMapsQuery": "Ollantaytambo Archeological Site, PPVM+6J7, Ollantaytambo 08676, Peru",
    "latitude": -13.2569661,
    "longitude": -72.26593969999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "30-60 min drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Ollantaytambo Archeological Site.",
    "priority": 3,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "552571440",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "30-60 min drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-731404160",
    "tripId": "peru-2026",
    "day": 4,
    "date": "2026-07-14",
    "city": "Ollantaytambo",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Inca Rail",
    "type": "transport",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Transit",
    "address": "PPPJ+Q9P, Ollantaytambo 08675, Peru",
    "googleMapsQuery": "Inca Rail, PPPJ+Q9P, Ollantaytambo 08675, Peru",
    "latitude": -13.2630441,
    "longitude": -72.2690555,
    "startTime": "16:26",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 638.75,
    "currency": "PEN",
    "costLocal": 638.75,
    "localCurrencyCode": "PEN",
    "costCad": 255.5,
    "costCategory": "transport",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Inca Rail.",
    "priority": 4,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "731404160",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-841263350",
    "tripId": "peru-2026",
    "day": 4,
    "date": "2026-07-14",
    "city": "Aguas Calientes",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Aguas Calientes",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "08681, Peru",
    "googleMapsQuery": "Aguas Calientes, 08681, Peru",
    "latitude": -13.1547062,
    "longitude": -72.5254412,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "30-60 min drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Aguas Calientes.",
    "priority": 5,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "841263350",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "30-60 min drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-518509593",
    "tripId": "peru-2026",
    "day": 5,
    "date": "2026-07-15",
    "city": "Peru",
    "region": "Peru",
    "country": "Peru",
    "title": "Historic Sanctuary of Machu Picchu",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "08680, Peru",
    "googleMapsQuery": "Historic Sanctuary of Machu Picchu, 08680, Peru",
    "latitude": -13.1631988,
    "longitude": -72.5452621,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 330.75,
    "currency": "PEN",
    "costLocal": 330.75,
    "localCurrencyCode": "PEN",
    "costCad": 132.3,
    "costCategory": "activity",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Historic Sanctuary of Machu Picchu.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "518509593",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-746124725",
    "tripId": "peru-2026",
    "day": 5,
    "date": "2026-07-15",
    "city": "Aguas Calientes",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Inca Rail - Machu Picchu Ticket Office",
    "type": "transport",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Transit",
    "address": "Estación de ferrocarril S/N, Aguas Calientes 08681, Peru",
    "googleMapsQuery": "Inca Rail - Machu Picchu Ticket Office, Estación de ferrocarril S/N, Aguas Calientes 08681, Peru",
    "latitude": -13.1556333,
    "longitude": -72.5245442,
    "startTime": "14:20",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "15-30 min local ride",
    "transportMode": "taxi/local transit",
    "estimatedCost": 638.75,
    "currency": "PEN",
    "costLocal": 638.75,
    "localCurrencyCode": "PEN",
    "costCad": 255.5,
    "costCategory": "transport",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Inca Rail - Machu Picchu Ticket Office.",
    "priority": 2,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "746124725",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "15-30 min local ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-502637856",
    "tripId": "peru-2026",
    "day": 5,
    "date": "2026-07-15",
    "city": "Ollantaytambo",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Ollantaytambo",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "Peru",
    "googleMapsQuery": "Ollantaytambo, Peru",
    "latitude": -13.258368899999999,
    "longitude": -72.2642679,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "30-60 min drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Ollantaytambo.",
    "priority": 3,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "502637856",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "30-60 min drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-818806039",
    "tripId": "peru-2026",
    "day": 5,
    "date": "2026-07-15",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Cusco",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Peru",
    "googleMapsQuery": "Cusco, Peru",
    "latitude": -13.53195,
    "longitude": -71.96746259999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "1-2 hr drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Cusco.",
    "priority": 4,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "818806039",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "1-2 hr drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-402025102",
    "tripId": "peru-2026",
    "day": 6,
    "date": "2026-07-16",
    "city": "Peru",
    "region": "Peru",
    "country": "Peru",
    "title": "Vinicunca",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "08225, Peru",
    "googleMapsQuery": "Vinicunca, 08225, Peru",
    "latitude": -13.870165799999999,
    "longitude": -71.3029901,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 597.5,
    "currency": "PEN",
    "costLocal": 597.5,
    "localCurrencyCode": "PEN",
    "costCad": 239,
    "costCategory": "activity",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Vinicunca.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "402025102",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-442374368",
    "tripId": "peru-2026",
    "day": 7,
    "date": "2026-07-17",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Plaza San Blas",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "F2MG+W7Q Cuesta de San Blas, Cusco 08003, Peru",
    "googleMapsQuery": "Plaza San Blas, F2MG+W7Q Cuesta de San Blas, Cusco 08003, Peru",
    "latitude": -13.515163399999999,
    "longitude": -71.9742527,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Plaza San Blas.",
    "priority": 1,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "442374368",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-724118835",
    "tripId": "peru-2026",
    "day": 7,
    "date": "2026-07-17",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Mercado Central de San Pedro",
    "type": "food",
    "description": "Food stop imported from the public Peru plan.",
    "category": "Food",
    "address": "Thupaq Amaru 477, Cusco 08002, Peru",
    "googleMapsQuery": "Mercado Central de San Pedro, Thupaq Amaru 477, Cusco 08002, Peru",
    "latitude": -13.520957699999999,
    "longitude": -71.9826676,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "food",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Mercado Central de San Pedro.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "724118835",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-158471446",
    "tripId": "peru-2026",
    "day": 8,
    "date": "2026-07-18",
    "city": "Peru",
    "region": "Peru",
    "country": "Peru",
    "title": "Ausangate 7 Lagunas",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Nevado auzangate Cusco, 08000, Peru",
    "googleMapsQuery": "Ausangate 7 Lagunas, Nevado auzangate Cusco, 08000, Peru",
    "latitude": -13.7582157,
    "longitude": -71.2187823,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 202.7,
    "currency": "PEN",
    "costLocal": 202.7,
    "localCurrencyCode": "PEN",
    "costCad": 81.08,
    "costCategory": "activity",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Ausangate 7 Lagunas.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "158471446",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-494541879",
    "tripId": "peru-2026",
    "day": 9,
    "date": "2026-07-19",
    "city": "Cusco",
    "region": "Cusco and Sacred Valley",
    "country": "Peru",
    "title": "Alejandro Velasco Astete International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Av. Velasco Astete, Cusco 08006, Peru",
    "googleMapsQuery": "Alejandro Velasco Astete International Airport, Av. Velasco Astete, Cusco 08006, Peru",
    "latitude": -13.538201899999999,
    "longitude": -71.94376989999999,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Alejandro Velasco Astete International Airport.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "494541879",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-845608099",
    "tripId": "peru-2026",
    "day": 9,
    "date": "2026-07-19",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Alfredo Rodriguez Ballon International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Av. Aeropuerto S/N, Cerro Colorado 04017, Peru",
    "googleMapsQuery": "Alfredo Rodriguez Ballon International Airport, Av. Aeropuerto S/N, Cerro Colorado 04017, Peru",
    "latitude": -16.3445567,
    "longitude": -71.5681872,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Airport transfer, confirm timing",
    "transportMode": "flight/airport",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Alfredo Rodriguez Ballon International Airport.",
    "priority": 2,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "845608099",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Exact route time missing from Wanderlog",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Airport transfer, confirm timing",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-785562843",
    "tripId": "peru-2026",
    "day": 9,
    "date": "2026-07-19",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Arequipa",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Peru",
    "googleMapsQuery": "Arequipa, Peru",
    "latitude": -16.4057001,
    "longitude": -71.5400994,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "15-30 min local ride",
    "transportMode": "taxi/local transit",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Arequipa.",
    "priority": 3,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "785562843",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "15-30 min local ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-224951053",
    "tripId": "peru-2026",
    "day": 9,
    "date": "2026-07-19",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Santa Catalina Monastery",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "Santa Catalina 301, Arequipa 04001, Peru",
    "googleMapsQuery": "Santa Catalina Monastery, Santa Catalina 301, Arequipa 04001, Peru",
    "latitude": -16.396109499999998,
    "longitude": -71.5365771,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Santa Catalina Monastery.",
    "priority": 4,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "224951053",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-609964107",
    "tripId": "peru-2026",
    "day": 9,
    "date": "2026-07-19",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Hotel Friendly AQP",
    "type": "hotel",
    "description": "Lodging stop imported from the public Peru plan.",
    "category": "Hotel",
    "address": "Ca. Consuelo 418, Arequipa 04001, Peru",
    "googleMapsQuery": "Hotel Friendly AQP, Ca. Consuelo 418, Arequipa 04001, Peru",
    "latitude": -16.400574499999998,
    "longitude": -71.5404465,
    "startTime": "",
    "endTime": "",
    "duration": "Check-in / stay",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 114,
    "currency": "PEN",
    "costLocal": 114,
    "localCurrencyCode": "PEN",
    "costCad": 45.6,
    "costCategory": "hotel",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Hotel Friendly AQP.",
    "priority": 5,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "609964107",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-114283583",
    "tripId": "peru-2026",
    "day": 10,
    "date": "2026-07-20",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Arequipa Colca Canyon | Private Transportation Perú",
    "type": "transport",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Transit",
    "address": "Arequipa 04501, Peru",
    "googleMapsQuery": "Arequipa Colca Canyon | Private Transportation Perú, Arequipa 04501, Peru",
    "latitude": -16.387348799999998,
    "longitude": -71.5240431,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 284.5,
    "currency": "PEN",
    "costLocal": 284.5,
    "localCurrencyCode": "PEN",
    "costCad": 113.8,
    "costCategory": "transport",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Arequipa Colca Canyon | Private Transportation Perú.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "114283583",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-709618099",
    "tripId": "peru-2026",
    "day": 10,
    "date": "2026-07-20",
    "city": "Chivay",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Chivay",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Peru",
    "googleMapsQuery": "Chivay, Peru",
    "latitude": -15.638845499999999,
    "longitude": -71.60204379999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "1-2 hr drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Chivay.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "709618099",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "1-2 hr drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-568156068",
    "tripId": "peru-2026",
    "day": 10,
    "date": "2026-07-20",
    "city": "Chivay",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "HOTEL LOS PORTALES DE CHIVAY",
    "type": "hotel",
    "description": "Lodging stop imported from the public Peru plan.",
    "category": "Hotel",
    "address": "Arequipa 603, Chivay, Peru",
    "googleMapsQuery": "HOTEL LOS PORTALES DE CHIVAY, Arequipa 603, Chivay, Peru",
    "latitude": -15.6396891,
    "longitude": -71.6012556,
    "startTime": "",
    "endTime": "",
    "duration": "Check-in / stay",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 140,
    "currency": "PEN",
    "costLocal": 140,
    "localCurrencyCode": "PEN",
    "costCad": 56,
    "costCategory": "hotel",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for HOTEL LOS PORTALES DE CHIVAY.",
    "priority": 3,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "568156068",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-911350027",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Lima",
    "region": "Lima",
    "country": "Peru",
    "title": "Mirador Cruz del Cóndor",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Las Peras 4356, Lima 15311, Peru",
    "googleMapsQuery": "Mirador Cruz del Cóndor, Las Peras 4356, Lima 15311, Peru",
    "latitude": -15.611288499999999,
    "longitude": -71.9060969,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Mirador Cruz del Cóndor.",
    "priority": 1,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "911350027",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-596552532",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Arequipa",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Peru",
    "googleMapsQuery": "Arequipa, Peru",
    "latitude": -16.4057001,
    "longitude": -71.5400994,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "1-2 hr drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Arequipa.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "596552532",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "1-2 hr drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-946839359",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Cerro Colorado",
    "region": "Peru",
    "country": "Peru",
    "title": "Ruta del Sillar",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "J9RV+495 Canteras Añashuayco, Cerro Colorado 04017, Peru",
    "googleMapsQuery": "Ruta del Sillar, J9RV+495 Canteras Añashuayco, Cerro Colorado 04017, Peru",
    "latitude": -16.3597362,
    "longitude": -71.6065002,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "30-60 min drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Ruta del Sillar.",
    "priority": 3,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "946839359",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "30-60 min drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-21543241",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "La Tasca",
    "type": "food",
    "description": "Food stop imported from the public Peru plan.",
    "category": "Food",
    "address": "Santa Catalina 503, Arequipa 04001, Peru",
    "googleMapsQuery": "La Tasca, Santa Catalina 503, Arequipa 04001, Peru",
    "latitude": -16.3938208,
    "longitude": -71.5357607,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "30-60 min drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "food",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for La Tasca.",
    "priority": 4,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "21543241",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "30-60 min drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-613676062",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Yanahuara",
    "region": "Peru",
    "country": "Peru",
    "title": "La Nueva Palomino",
    "type": "food",
    "description": "Food stop imported from the public Peru plan.",
    "category": "Food",
    "address": "Leoncio Prado 122, Yanahuara 04000, Peru",
    "googleMapsQuery": "La Nueva Palomino, Leoncio Prado 122, Yanahuara 04000, Peru",
    "latitude": -16.387075,
    "longitude": -71.5395465,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "food",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for La Nueva Palomino.",
    "priority": 5,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "613676062",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-806738444",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Il Caffè Della Nonna",
    "type": "food",
    "description": "Food stop imported from the public Peru plan.",
    "category": "Food",
    "address": "Casona Flores del Campo, Pl. de Armas, Arequipa 04001, Peru",
    "googleMapsQuery": "Il Caffè Della Nonna, Casona Flores del Campo, Pl. de Armas, Arequipa 04001, Peru",
    "latitude": -16.3992784,
    "longitude": -71.536372,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "food",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Il Caffè Della Nonna.",
    "priority": 6,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "806738444",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-410693158",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Queso Helado Doña Rosa",
    "type": "food",
    "description": "Food stop imported from the public Peru plan.",
    "category": "Food",
    "address": "Mercado San Camilo .Puesto 1 Segundo Piso, La Seccion De Flores Cercado, Arequipa 04001, Peru",
    "googleMapsQuery": "Queso Helado Doña Rosa, Mercado San Camilo .Puesto 1 Segundo Piso, La Seccion De Flores Cercado, Arequipa 04001, Peru",
    "latitude": -16.402711699999998,
    "longitude": -71.5350029,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "food",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Queso Helado Doña Rosa.",
    "priority": 7,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "410693158",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-125598066",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Plaza de Armas Arequipa",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Arequipa 04001, Peru",
    "googleMapsQuery": "Plaza de Armas Arequipa, Arequipa 04001, Peru",
    "latitude": -16.3988583,
    "longitude": -71.5369174,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Plaza de Armas Arequipa.",
    "priority": 8,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "125598066",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-561769102",
    "tripId": "peru-2026",
    "day": 11,
    "date": "2026-07-21",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Hotel Friendly AQP",
    "type": "hotel",
    "description": "Lodging stop imported from the public Peru plan.",
    "category": "Hotel",
    "address": "Ca. Consuelo 418, Arequipa 04001, Peru",
    "googleMapsQuery": "Hotel Friendly AQP, Ca. Consuelo 418, Arequipa 04001, Peru",
    "latitude": -16.400574499999998,
    "longitude": -71.5404465,
    "startTime": "",
    "endTime": "",
    "duration": "Check-in / stay",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 228,
    "currency": "PEN",
    "costLocal": 228,
    "localCurrencyCode": "PEN",
    "costCad": 91.2,
    "costCategory": "hotel",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Hotel Friendly AQP.",
    "priority": 9,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "561769102",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-677684701",
    "tripId": "peru-2026",
    "day": 12,
    "date": "2026-07-22",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Mundo Alpaca",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Alameda San Lázaro 101, Arequipa 04001, Peru",
    "googleMapsQuery": "Mundo Alpaca, Alameda San Lázaro 101, Arequipa 04001, Peru",
    "latitude": -16.3929231,
    "longitude": -71.5354539,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Mundo Alpaca.",
    "priority": 1,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "677684701",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-32970489",
    "tripId": "peru-2026",
    "day": 12,
    "date": "2026-07-22",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Museo Santuarios Andinos",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "C. la Merced 110, Arequipa 04001, Peru",
    "googleMapsQuery": "Museo Santuarios Andinos, C. la Merced 110, Arequipa 04001, Peru",
    "latitude": -16.3999611,
    "longitude": -71.53775499999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Museo Santuarios Andinos.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "32970489",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-562023629",
    "tripId": "peru-2026",
    "day": 12,
    "date": "2026-07-22",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Hotel Friendly AQP",
    "type": "hotel",
    "description": "Lodging stop imported from the public Peru plan.",
    "category": "Hotel",
    "address": "Ca. Consuelo 418, Arequipa 04001, Peru",
    "googleMapsQuery": "Hotel Friendly AQP, Ca. Consuelo 418, Arequipa 04001, Peru",
    "latitude": -16.400574499999998,
    "longitude": -71.5404465,
    "startTime": "",
    "endTime": "",
    "duration": "Check-in / stay",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "hotel",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Hotel Friendly AQP.",
    "priority": 3,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "562023629",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-59857745",
    "tripId": "peru-2026",
    "day": 13,
    "date": "2026-07-23",
    "city": "Arequipa",
    "region": "Arequipa and Colca",
    "country": "Peru",
    "title": "Alfredo Rodriguez Ballon International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Av. Aeropuerto S/N, Cerro Colorado 04017, Peru",
    "googleMapsQuery": "Alfredo Rodriguez Ballon International Airport, Av. Aeropuerto S/N, Cerro Colorado 04017, Peru",
    "latitude": -16.3445567,
    "longitude": -71.5681872,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Alfredo Rodriguez Ballon International Airport.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "59857745",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-784011187",
    "tripId": "peru-2026",
    "day": 13,
    "date": "2026-07-23",
    "city": "Lima",
    "region": "Lima",
    "country": "Peru",
    "title": "New Jorge Chávez International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Avenida Morales Duárez s/n, Callao, Peru",
    "googleMapsQuery": "New Jorge Chávez International Airport, Avenida Morales Duárez s/n, Callao, Peru",
    "latitude": -12.029701099999999,
    "longitude": -77.11622779999999,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Airport transfer, confirm timing",
    "transportMode": "flight/airport",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for New Jorge Chávez International Airport.",
    "priority": 2,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "784011187",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Exact route time missing from Wanderlog",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Airport transfer, confirm timing",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-655112224",
    "tripId": "peru-2026",
    "day": 13,
    "date": "2026-07-23",
    "city": "Paracas",
    "region": "Coast and desert",
    "country": "Peru",
    "title": "Paracas",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "11550, Peru",
    "googleMapsQuery": "Paracas, 11550, Peru",
    "latitude": -13.8331701,
    "longitude": -76.24778649999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "2-5 hr transfer",
    "transportMode": "car/bus/train",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Paracas.",
    "priority": 3,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "655112224",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "2-5 hr transfer",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-696308337",
    "tripId": "peru-2026",
    "day": 13,
    "date": "2026-07-23",
    "city": "Paracas",
    "region": "Coast and desert",
    "country": "Peru",
    "title": "Paracas Backpacker's House",
    "type": "hotel",
    "description": "Lodging stop imported from the public Peru plan.",
    "category": "Hotel",
    "address": "Playa, Paracas, Peru",
    "googleMapsQuery": "Paracas Backpacker's House, Playa, Paracas, Peru",
    "latitude": -13.8341766,
    "longitude": -76.2484467,
    "startTime": "",
    "endTime": "",
    "duration": "Check-in / stay",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 77.72,
    "currency": "PEN",
    "costLocal": 77.72,
    "localCurrencyCode": "PEN",
    "costCad": 31.09,
    "costCategory": "hotel",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Paracas Backpacker's House.",
    "priority": 4,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "696308337",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-354920102",
    "tripId": "peru-2026",
    "day": 14,
    "date": "2026-07-24",
    "city": "Peru",
    "region": "Peru",
    "country": "Peru",
    "title": "Islas Ballestas",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "Peru",
    "googleMapsQuery": "Islas Ballestas, Peru",
    "latitude": -13.731831399999999,
    "longitude": -76.3977304,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 142.25,
    "currency": "PEN",
    "costLocal": 142.25,
    "localCurrencyCode": "PEN",
    "costCad": 56.9,
    "costCategory": "activity",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Islas Ballestas.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "354920102",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-771785734",
    "tripId": "peru-2026",
    "day": 14,
    "date": "2026-07-24",
    "city": "Huacachina",
    "region": "Coast and desert",
    "country": "Peru",
    "title": "Huacachina Oasis",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "Unnamed Road, Huacachina 11000, Peru",
    "googleMapsQuery": "Huacachina Oasis, Unnamed Road, Huacachina 11000, Peru",
    "latitude": -14.0873523,
    "longitude": -75.76310579999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "1-2 hr drive",
    "transportMode": "car",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Huacachina Oasis.",
    "priority": 2,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "771785734",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "1-2 hr drive",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-588890765",
    "tripId": "peru-2026",
    "day": 14,
    "date": "2026-07-24",
    "city": "Ica",
    "region": "Coast and desert",
    "country": "Peru",
    "title": "Huacachina Sandboard",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Must See",
    "address": "Huacachina, Av. Ángela Perotti, Ica 11000, Peru",
    "googleMapsQuery": "Huacachina Sandboard, Huacachina, Av. Ángela Perotti, Ica 11000, Peru",
    "latitude": -14.0885556,
    "longitude": -75.76240829999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 355.65,
    "currency": "PEN",
    "costLocal": 355.65,
    "localCurrencyCode": "PEN",
    "costCad": 142.26,
    "costCategory": "activity",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Huacachina Sandboard.",
    "priority": 3,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "588890765",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time",
      "Start time missing"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-179851653",
    "tripId": "peru-2026",
    "day": 14,
    "date": "2026-07-24",
    "city": "Huacachina",
    "region": "Coast and desert",
    "country": "Peru",
    "title": "Wild Rover Huacachina",
    "type": "hotel",
    "description": "Lodging stop imported from the public Peru plan.",
    "category": "Hotel",
    "address": "Av. Angela de Perotti S/N Balneario de, Huacachina, Peru",
    "googleMapsQuery": "Wild Rover Huacachina, Av. Angela de Perotti S/N Balneario de, Huacachina, Peru",
    "latitude": -14.086532499999999,
    "longitude": -75.7628489,
    "startTime": "",
    "endTime": "",
    "duration": "Check-in / stay",
    "travelTimeFromPrevious": "5-15 min walk or ride",
    "transportMode": "walk/ride",
    "estimatedCost": 195.9,
    "currency": "PEN",
    "costLocal": 195.9,
    "localCurrencyCode": "PEN",
    "costCad": 78.36,
    "costCategory": "hotel",
    "costStatus": "converted-estimate",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Wild Rover Huacachina.",
    "priority": 4,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "179851653",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Heuristic route time"
    ],
    "routeLegEstimate": "5-15 min walk or ride",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-241419926",
    "tripId": "peru-2026",
    "day": 15,
    "date": "2026-07-25",
    "city": "Lima",
    "region": "Lima",
    "country": "Peru",
    "title": "Lima",
    "type": "activity",
    "description": "Wanderlog stop imported from the public Peru plan.",
    "category": "Nice To Have",
    "address": "Peru",
    "googleMapsQuery": "Lima, Peru",
    "latitude": -12.0466888,
    "longitude": -77.04308859999999,
    "startTime": "",
    "endTime": "",
    "duration": "Timing needs confirmation",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "activity",
    "costStatus": "needs-confirmation",
    "bookingStatus": "needs-confirmation",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Lima.",
    "priority": 1,
    "isBooked": false,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "241419926",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-579604563",
    "tripId": "peru-2026",
    "day": 16,
    "date": "2026-07-26",
    "city": "Lima",
    "region": "Lima",
    "country": "Peru",
    "title": "New Jorge Chávez International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Avenida Morales Duárez s/n, Callao, Peru",
    "googleMapsQuery": "New Jorge Chávez International Airport, Avenida Morales Duárez s/n, Callao, Peru",
    "latitude": -12.029701099999999,
    "longitude": -77.11622779999999,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Start of day",
    "transportMode": "start",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for New Jorge Chávez International Airport.",
    "priority": 1,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "579604563",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Start of day",
    "isRouteEstimate": false
  },
  {
    "id": "peru-wanderlog-290212206",
    "tripId": "peru-2026",
    "day": 16,
    "date": "2026-07-26",
    "city": "Cancun",
    "region": "Flight connection",
    "country": "Mexico",
    "title": "Cancun International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "Carr. a Aeropuerto Cancún, 77500 Cancún, Q.R., Mexico",
    "googleMapsQuery": "Cancun International Airport, Carr. a Aeropuerto Cancún, 77500 Cancún, Q.R., Mexico",
    "latitude": 21.0419232,
    "longitude": -86.8743844,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Airport transfer, confirm timing",
    "transportMode": "flight/airport",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Cancun International Airport.",
    "priority": 2,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "290212206",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Exact route time missing from Wanderlog",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Airport transfer, confirm timing",
    "isRouteEstimate": true
  },
  {
    "id": "peru-wanderlog-679009226",
    "tripId": "peru-2026",
    "day": 16,
    "date": "2026-07-26",
    "city": "Toronto",
    "region": "Flight connection",
    "country": "Canada",
    "title": "Toronto Pearson International Airport",
    "type": "flight",
    "description": "Airport leg imported from the public Peru plan.",
    "category": "Flight",
    "address": "6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada",
    "googleMapsQuery": "Toronto Pearson International Airport, 6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada",
    "latitude": 43.6798345,
    "longitude": -79.62838339999999,
    "startTime": "",
    "endTime": "",
    "duration": "Airport leg",
    "travelTimeFromPrevious": "Airport transfer, confirm timing",
    "transportMode": "flight/airport",
    "estimatedCost": 0,
    "currency": "PEN",
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "costCad": 0,
    "costCategory": "flight",
    "costStatus": "needs-confirmation",
    "bookingStatus": "booked",
    "bookingReference": "",
    "confirmationReference": "",
    "attachmentIds": [],
    "notes": "",
    "imageUrl": "",
    "imageAlt": "Image-style fallback for Toronto Pearson International Airport.",
    "priority": 3,
    "isBooked": true,
    "isCompleted": false,
    "source": "Wanderlog",
    "sourceId": "679009226",
    "sourceUrl": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "needsConfirmationReasons": [
      "Exact route time missing from Wanderlog",
      "Cost needs confirmation",
      "Start time missing"
    ],
    "routeLegEstimate": "Airport transfer, confirm timing",
    "isRouteEstimate": true
  }
].map((activity) => ({
  ...activity,
  imageUrl: activity.imageUrl || scenic(activity.title),
}) as TripActivity);

export const peruFlights: TripFlight[] = [
  {
    "id": "peru-flight-461505389",
    "tripId": "peru-2026",
    "airline": "Air Canada",
    "flightNumber": "AC1810",
    "departureAirport": "Toronto Pearson International Airport (YYZ)",
    "arrivalAirport": "Cancun International Airport (CUN)",
    "departureTime": "2026-07-11T07:15:00",
    "arrivalTime": "2026-07-11T10:15:00",
    "confirmation": "",
    "status": "manual / not live yet",
    "notes": "Imported from Wanderlog flight section. Status is manual, not live.",
    "costCad": 1813.82,
    "costLocal": 4534.55,
    "localCurrencyCode": "PEN",
    "source": "Wanderlog",
    "sourceId": "461505389"
  },
  {
    "id": "peru-flight-792593333",
    "tripId": "peru-2026",
    "airline": "LATAM Airlines",
    "flightNumber": "LA2459",
    "departureAirport": "Cancun International Airport (CUN)",
    "arrivalAirport": "Lima Jorge Chavez International Airport (LIM)",
    "departureTime": "2026-07-11T15:25:00",
    "arrivalTime": "2026-07-11T20:40:00",
    "confirmation": "",
    "status": "manual / not live yet",
    "notes": "Imported from Wanderlog flight section. Status is manual, not live.",
    "costCad": 1813.82,
    "costLocal": 4534.55,
    "localCurrencyCode": "PEN",
    "source": "Wanderlog",
    "sourceId": "792593333"
  },
  {
    "id": "peru-flight-179151877",
    "tripId": "peru-2026",
    "airline": "LATAM Airlines",
    "flightNumber": "LA2454",
    "departureAirport": "Lima Jorge Chavez International Airport (LIM)",
    "arrivalAirport": "Cancun International Airport (CUN)",
    "departureTime": "2026-07-26T10:45:00",
    "arrivalTime": "2026-07-26T16:15:00",
    "confirmation": "",
    "status": "manual / not live yet",
    "notes": "Imported from Wanderlog flight section. Status is manual, not live.",
    "costCad": 0,
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "source": "Wanderlog",
    "sourceId": "179151877"
  },
  {
    "id": "peru-flight-194098485",
    "tripId": "peru-2026",
    "airline": "WestJet",
    "flightNumber": "WS2131",
    "departureAirport": "Cancun International Airport (CUN)",
    "arrivalAirport": "Toronto Pearson International Airport (YYZ)",
    "departureTime": "2026-07-26T19:40:00",
    "arrivalTime": "2026-07-27T00:40:00",
    "confirmation": "",
    "status": "manual / not live yet",
    "notes": "Imported from Wanderlog flight section. Status is manual, not live.",
    "costCad": 0,
    "costLocal": 0,
    "localCurrencyCode": "PEN",
    "source": "Wanderlog",
    "sourceId": "194098485"
  }
];

export const peruHotels: TripHotel[] = [
  {
    "id": "peru-hotel-515698313",
    "tripId": "peru-2026",
    "name": "Samay Wasi Youth Hostels Cusco",
    "city": "Cusco",
    "country": "Peru",
    "address": "Atoqsayk'uchi 416, Cusco 08003, Peru",
    "checkIn": "2026-07-11",
    "checkOut": "2026-07-13",
    "estimatedCost": 189.7,
    "currency": "PEN",
    "costCad": 75.88,
    "costLocal": 189.7,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "515698313",
    "confirmation": "8830-574775503",
    "notes": "Imported lodging cost from Wanderlog.",
    "latitude": -13.512908999999999,
    "longitude": -71.9753348
  },
  {
    "id": "peru-hotel-777893293",
    "tripId": "peru-2026",
    "name": "Casa Inka B&B",
    "city": "Ollantaytambo",
    "country": "Peru",
    "address": "Correo postal de ollantaytambo, Ollantaytambo 08676, Peru",
    "checkIn": "2026-07-13",
    "checkOut": "2026-07-14",
    "estimatedCost": 112.5,
    "currency": "PEN",
    "costCad": 45,
    "costLocal": 112.5,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "777893293",
    "confirmation": "6846218566",
    "notes": "Imported lodging cost from Wanderlog.",
    "latitude": -13.2590788,
    "longitude": -72.2604527
  },
  {
    "id": "peru-hotel-942777819",
    "tripId": "peru-2026",
    "name": "Hotel INKA'S LAND",
    "city": "Aguas Calientes",
    "country": "Peru",
    "address": "Ca. Chaska Tika 111, Aguas Calientes 08681, Peru",
    "checkIn": "2026-07-14",
    "checkOut": "2026-07-15",
    "estimatedCost": 133.65,
    "currency": "PEN",
    "costCad": 53.46,
    "costLocal": 133.65,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "942777819",
    "confirmation": "574783520",
    "notes": "32.73 usd payable",
    "latitude": -13.1563676,
    "longitude": -72.523293
  },
  {
    "id": "peru-hotel-976437118",
    "tripId": "peru-2026",
    "name": "Samay Wasi Youth Hostels Cusco",
    "city": "Cusco",
    "country": "Peru",
    "address": "Atoqsayk'uchi 416, Cusco 08003, Peru",
    "checkIn": "2026-07-15",
    "checkOut": "2026-07-19",
    "estimatedCost": 385.98,
    "currency": "PEN",
    "costCad": 154.39,
    "costLocal": 385.98,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "976437118",
    "confirmation": "574789492",
    "notes": "90.20 USD payable",
    "latitude": -13.512908999999999,
    "longitude": -71.9753348
  },
  {
    "id": "peru-hotel-279946819",
    "tripId": "peru-2026",
    "name": "Hotel Friendly AQP",
    "city": "Arequipa",
    "country": "Peru",
    "address": "Ca. Consuelo 418, Arequipa 04001, Peru",
    "checkIn": "2026-07-19",
    "checkOut": "2026-07-20",
    "estimatedCost": 114,
    "currency": "PEN",
    "costCad": 45.6,
    "costLocal": 114,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "279946819",
    "confirmation": "81894-574760487",
    "notes": "89.10 sol payable",
    "latitude": -16.400574499999998,
    "longitude": -71.5404465
  },
  {
    "id": "peru-hotel-819930582",
    "tripId": "peru-2026",
    "name": "HOTEL LOS PORTALES DE CHIVAY",
    "city": "Chivay",
    "country": "Peru",
    "address": "Arequipa 603, Chivay, Peru",
    "checkIn": "2026-07-20",
    "checkOut": "2026-07-21",
    "estimatedCost": 140,
    "currency": "PEN",
    "costCad": 56,
    "costLocal": 140,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "819930582",
    "confirmation": "5489126910",
    "notes": "Imported lodging cost from Wanderlog.",
    "latitude": -15.6396891,
    "longitude": -71.6012556
  },
  {
    "id": "peru-hotel-401589952",
    "tripId": "peru-2026",
    "name": "Hotel Friendly AQP",
    "city": "Arequipa",
    "country": "Peru",
    "address": "Ca. Consuelo 418, Arequipa 04001, Peru",
    "checkIn": "2026-07-21",
    "checkOut": "2026-07-23",
    "estimatedCost": 228,
    "currency": "PEN",
    "costCad": 91.2,
    "costLocal": 228,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "401589952",
    "confirmation": "81894-574760513",
    "notes": "178.20 sol",
    "latitude": -16.400574499999998,
    "longitude": -71.5404465
  },
  {
    "id": "peru-hotel-774814261",
    "tripId": "peru-2026",
    "name": "Paracas Backpacker's House",
    "city": "Paracas",
    "country": "Peru",
    "address": "Playa, Paracas, Peru",
    "checkIn": "2026-07-23",
    "checkOut": "2026-07-24",
    "estimatedCost": 77.72,
    "currency": "PEN",
    "costCad": 31.09,
    "costLocal": 77.72,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "774814261",
    "confirmation": "305417-574739374",
    "notes": "63.75 sol",
    "latitude": -13.8341766,
    "longitude": -76.2484467
  },
  {
    "id": "peru-hotel-976764669",
    "tripId": "peru-2026",
    "name": "Wild Rover Huacachina",
    "city": "Huacachina",
    "country": "Peru",
    "address": "Av. Angela de Perotti S/N Balneario de, Huacachina, Peru",
    "checkIn": "2026-07-24",
    "checkOut": "2026-07-25",
    "estimatedCost": 195.9,
    "currency": "PEN",
    "costCad": 78.36,
    "costLocal": 195.9,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "976764669",
    "confirmation": "292424-574737330",
    "notes": "158.76 sol",
    "latitude": -14.086532499999999,
    "longitude": -75.7628489
  },
  {
    "id": "peru-hotel-833484532",
    "tripId": "peru-2026",
    "name": "Alpes Lima Kennedy Park",
    "city": "Miraflores",
    "country": "Peru",
    "address": "Calle Porta 145, Miraflores 15074, Peru",
    "checkIn": "2026-07-25",
    "checkOut": "2026-07-26",
    "estimatedCost": 167.08,
    "currency": "PEN",
    "costCad": 66.83,
    "costLocal": 167.08,
    "localCurrencyCode": "PEN",
    "costStatus": "converted-estimate",
    "source": "Wanderlog",
    "sourceId": "833484532",
    "confirmation": "277492-574784650",
    "notes": "126.40 sol payable. might need to cancel due to far distance from airport",
    "latitude": -12.1234398,
    "longitude": -77.0312259
  }
];

export const peruTransitBookings = [
  {
    "id": 516472297,
    "carrier": "Inca Rail",
    "depart": "Ollantaytambo",
    "arrive": "Aguas Calientes",
    "date": "2026-07-14",
    "time": "16:06",
    "confirmationNumber": "K9V7O9",
    "costCad": 255.5
  },
  {
    "id": 132805181,
    "carrier": "INCA RAIL",
    "depart": "Aguas Calientes",
    "arrive": "Ollantaytambo",
    "date": "2026-07-15",
    "time": "14:00",
    "confirmationNumber": "T6J7R8",
    "costCad": 255.5
  }
];

export const peruAttachments: TripAttachment[] = [
  {
    "id": "peru-google-doc-source",
    "tripId": "peru-2026",
    "fileName": "google-doc-source-needs-export.md",
    "type": "note",
    "note": "Google Doc could not be read directly. Paste or export it into the import panel.",
    "url": "https://docs.google.com/document/d/1huAZVsFsUmAh80jzrkG6IzBke6sNUKhoJp3wjIOjJfI/edit?tab=t.ydmxzx6uluaw",
    "isSensitivePlaceholder": false
  },
  {
    "id": "peru-wanderlog-source",
    "tripId": "peru-2026",
    "fileName": "wanderlog-public-plan.json",
    "type": "note",
    "note": "Public Wanderlog state imported: 16 days, 55 dated cards, 4 flights, 10 hotels, 19 expenses.",
    "url": "https://wanderlog.com/plan/ovvfbwnqqrtasylt/trip-to-peru",
    "isSensitivePlaceholder": false
  },
  {
    "id": "peru-booking-placeholders",
    "tripId": "peru-2026",
    "fileName": "booking-confirmations-placeholder.pdf",
    "type": "booking",
    "note": "Metadata only. Do not store passports, visa scans, or private IDs in localStorage.",
    "isSensitivePlaceholder": true
  }
];

export const peruRouteSuggestions: RouteSuggestion[] = [
  {
    "id": "peru-google-doc-needs-export",
    "tripId": "peru-2026",
    "severity": "info",
    "title": "Google Doc needs paste or export",
    "detail": "Google redirected the document export to sign-in, so only the public Wanderlog note was imported."
  },
  {
    "id": "peru-travel-times-heuristic",
    "tripId": "peru-2026",
    "severity": "warning",
    "title": "Route times are estimates",
    "detail": "Wanderlog did not expose per-leg durations publicly. Connectors use distance-based planning estimates until confirmed."
  },
  {
    "id": "peru-drivers-warning",
    "tripId": "peru-2026",
    "severity": "warning",
    "title": "Book flights and drivers",
    "detail": "Imported Wanderlog note says: need to book flights and drivers."
  }
];

export const peruTrip: Trip = {
  id: "peru-2026",
  title: "Peru Trip",
  country: "Peru",
  startDate: "2026-07-11",
  endDate: "2026-07-26",
  currency: "PEN",
  currencyConfig: {
    localCurrency: "PEN",
    comparisonCurrency: "CAD",
    localPerCad: PERU_CAD_TO_PEN,
    label: "PEN per 1 CAD",
    isEstimate: true,
  },
  description: "A Wanderlog-imported July 2026 Peru route with daily stops, flights, lodging, costs, route estimates, and export-ready map rows.",
  activities: peruActivities,
  flights: peruFlights,
  hotels: peruHotels,
  attachments: peruAttachments,
  notes: "https://docs.google.com/document/d/1huAZVsFsUmAh80jzrkG6IzBke6sNUKhoJp3wjIOjJfI/edit?tab=t.ydmxzx6uluaw\n\nneed to book flights and drivers\n\nGoogle Doc source requires paste/export before importing extra notes: https://docs.google.com/document/d/1huAZVsFsUmAh80jzrkG6IzBke6sNUKhoJp3wjIOjJfI/edit?tab=t.ydmxzx6uluaw",
};
