import type { RouteSuggestion, Trip, TripActivity, TripAttachment, TripFlight, TripHotel } from "./tripTypes";

export const PORTUGAL_CAD_TO_EUR = 0.65;
export const PORTUGAL_WANDERLOG_PDF_SOURCE = "/Users/nhihad/Downloads/Trip to Portugal – Wanderlog.pdf";
export const PORTUGAL_GOOGLE_DOC_PDF_SOURCE = "/Users/nhihad/Downloads/Portugal_Mainland_Trip_Itinerary_June_2026.docx.pdf";

const scenic = (name: string) =>
  `linear-gradient(135deg, hsl(${Math.abs([...name].reduce((sum, char) => sum + char.charCodeAt(0), 0)) % 360} 44% 84%) 0%, #f6efe3 52%, #ddeee8 100%)`;

const commonsFile = (fileName: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(fileName)}?width=1200`;

const commonsPage = (fileName: string) =>
  `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(fileName.replace(/ /g, "_"))}`;

function commonsImage(fileName: string, alt: string, searchQuery: string): Partial<TripActivity> {
  return {
    imageUrl: commonsFile(fileName),
    imageAlt: alt,
    imageCredit: "Wikimedia Commons",
    imageCreditUrl: commonsPage(fileName),
    imageLicense: "See Wikimedia Commons file page",
    imageSearchQuery: searchQuery,
  };
}

const portugalImageCatalog: Record<string, Partial<TripActivity>> = {
  Lisbon: commonsImage("View of Lisbon and azulejo panel, São Pedro de Alcântara viewpoint, Lisbon, Portugal julesvernex2.jpg", "Lisbon rooftops and the Tagus River.", "Lisbon Portugal viewpoint"),
  "Belém Tower": commonsImage("Torre Belém April 2009-4a.jpg", "Belém Tower in Lisbon.", "Belem Tower Lisbon Portugal"),
  "Monument to the Discoveries": commonsImage("Rosa-dos-ventos.JPG", "Monument to the Discoveries in Lisbon.", "Padrao dos Descobrimentos Lisbon"),
  "Pastéis de Belém": commonsImage("Pasteis de Belem, Lisbon, Portugal.JPG", "Pastel de nata pastries in Lisbon.", "Pasteis de Belem Lisbon"),
  "Jerónimos Monastery": commonsImage("Jerónimos Monastery in Belém, Lisbon, 20250604 1342 9260.jpg", "Jerónimos Monastery in Lisbon.", "Jeronimos Monastery Lisbon"),
  "LX Factory": commonsImage("LX Factory Lisbon (44543156954).jpg", "LX Factory in Lisbon.", "LX Factory Lisbon"),
  "Time Out Market": commonsImage("Time Out Market, Lisbon (34263715400).jpg", "Mercado da Ribeira and Time Out Market in Lisbon.", "Time Out Market Lisbon"),
  "Eduardo VII Park": commonsImage("Azulejos Parque Eduardo VII-1.jpg", "Eduardo VII Park in Lisbon.", "Eduardo VII Park Lisbon"),
  "Oceanário de Lisboa": commonsImage("Oceanario Lisboa 2008.jpg", "Oceanario de Lisboa in Parque das Nacoes.", "Oceanario de Lisboa"),
  "Centro Vasco da Gama": commonsImage("Vasco da Gama Jerónimos 2008-1.jpg", "Centro Vasco da Gama in Lisbon.", "Centro Vasco da Gama Lisbon"),
  "Castelo de São Jorge": commonsImage("Castelo de São Jorge, Lisbon, Portugal.jpg", "Castelo de Sao Jorge above Lisbon.", "Castelo de Sao Jorge Lisbon"),
  "Miradouro da Senhora do Monte": commonsImage("Miradouro da Senhora do Monte Lisboa.jpg", "View from Miradouro da Senhora do Monte.", "Miradouro da Senhora do Monte Lisbon"),
  "Miradouro de Santa Luzia": commonsImage("Miradouro de Santa Luzia Lisbon.jpg", "Miradouro de Santa Luzia in Lisbon.", "Miradouro Santa Luzia Lisbon"),
  "Lisbon Cathedral": commonsImage("Sé de Lisboa, Portugal.jpg", "Lisbon Cathedral exterior.", "Lisbon Cathedral Portugal"),
  "Miradouro de São Pedro de Alcântara": commonsImage("Miradouro de São Pedro de Alcântara Lisboa.jpg", "Miradouro de Sao Pedro de Alcantara in Lisbon.", "Miradouro Sao Pedro de Alcantara Lisbon"),
  "Calouste Gulbenkian Museum": commonsImage("Fundação Calouste Gulbenkian, Lisboa.jpg", "Calouste Gulbenkian Museum in Lisbon.", "Calouste Gulbenkian Museum Lisbon"),
  "Santa Justa Lift": commonsImage("Elevador de Santa Justa Lisbon.jpg", "Santa Justa Lift in Lisbon.", "Santa Justa Lift Lisbon"),
  "Rua Augusta Arch": commonsImage("Arco da Rua Augusta, Lisbon, Portugal.jpg", "Rua Augusta Arch in Lisbon.", "Rua Augusta Arch Lisbon"),
  "Museu Nacional do Azulejo": commonsImage("Museu Nacional do Azulejo Lisboa.jpg", "Tile panels inside the National Tile Museum.", "Museu Nacional do Azulejo Lisbon"),
  "National Pantheon": commonsImage("Panteão Nacional Lisboa.jpg", "National Pantheon in Lisbon.", "National Pantheon Lisbon"),
  "Miradouro da Graça": commonsImage("Miradouro da Graça Lisboa.jpg", "Miradouro da Graca viewpoint in Lisbon.", "Miradouro da Graca Lisbon"),
  "Tram 28": commonsImage("Lisbon tram 28.jpg", "Classic yellow Tram 28 in Lisbon.", "Tram 28 Lisbon"),
  "Estufa Fria": commonsImage("Estufa Fria Lisboa.jpg", "Estufa Fria gardens in Lisbon.", "Estufa Fria Lisbon"),
  "Ponte 25 de Abril": commonsImage("Ponte 25 de Abril Lisboa.jpg", "Ponte 25 de Abril over the Tagus River.", "Ponte 25 de Abril Lisbon"),
  "MAAT - Museum of Art, Architecture and Technology": commonsImage("MAAT Lisboa.jpg", "MAAT museum on the Lisbon waterfront.", "MAAT Lisbon"),
  "Palácio Nacional da Ajuda": commonsImage("Palácio Nacional da Ajuda Lisboa.jpg", "Ajuda National Palace in Lisbon.", "Palacio Nacional da Ajuda Lisbon"),
  "National Coach Museum": commonsImage("Museu Nacional dos Coches Lisboa.jpg", "National Coach Museum in Lisbon.", "National Coach Museum Lisbon"),
  "Basilica of Estrela": commonsImage("Basílica da Estrela Lisboa.jpg", "Basilica da Estrela in Lisbon.", "Basilica da Estrela Lisbon"),
  "National Museum of Ancient Art": commonsImage("Museu Nacional de Arte Antiga Lisboa.jpg", "National Museum of Ancient Art in Lisbon.", "Museu Nacional de Arte Antiga Lisbon"),
  "Pink Street": commonsImage("Pink Street Lisbon.jpg", "Pink Street in Lisbon.", "Pink Street Lisbon"),
  "Santo António festival night": commonsImage("Santo Antonio Lisbon festival.jpg", "Lisbon street festival atmosphere.", "Santo Antonio festival Lisbon"),
  Lagos: commonsImage("Lagos Portugal coastline.jpg", "Lagos coastline in the Algarve.", "Lagos Algarve Portugal"),
  "Ponta da Piedade": commonsImage("Ponta da Piedade, Lagos (20518421738).jpg", "Ponta da Piedade cliffs near Lagos.", "Ponta da Piedade Lagos"),
  "Praia do Camilo": commonsImage("Strand Praia do camilo Lagos (27711818845) (2).jpg", "Praia do Camilo near Lagos.", "Praia do Camilo Lagos"),
  "Praia Dona Ana": commonsImage("Praia Dona Ana Lagos Portugal.jpg", "Praia Dona Ana in Lagos.", "Praia Dona Ana Lagos"),
  "Porto Mós Beach": commonsImage("Praia de Porto de Mos Lagos.jpg", "Porto Mos Beach in Lagos.", "Porto Mos Beach Lagos"),
  "Praia do Pinhão": commonsImage("Praia do Pinhao Lagos Portugal.jpg", "Praia do Pinhao near Lagos.", "Praia do Pinhao Lagos"),
  "Beach Estudantes": commonsImage("Praia dos Estudantes Lagos Portugal.jpg", "Praia dos Estudantes in Lagos.", "Praia dos Estudantes Lagos"),
  "Mercado Municipal de Lagos": commonsImage("Mercado Municipal de Lagos Portugal.jpg", "Municipal market in Lagos.", "Mercado Municipal de Lagos"),
  "Seven Hanging Valleys hike": commonsImage("Praia da Marinha Algarve Portugal.jpg", "Cliffs near Praia da Marinha on the Seven Hanging Valleys route.", "Seven Hanging Valleys Algarve"),
  "Sagres surf option": commonsImage("Sagres Portugal coast.jpg", "Sagres coastline in the Algarve.", "Sagres surf Portugal"),
  Sintra: commonsImage("Pena Palace Sintra.jpg", "Pena Palace in Sintra.", "Pena Palace Sintra"),
  "Quinta da Regaleira": commonsImage("Initiation Well in Quinta da Regaleira - Sintra (15845121413).jpg", "Initiation Well at Quinta da Regaleira.", "Quinta da Regaleira Sintra"),
  "Monserrate Palace": commonsImage("Monserrate Palace Sintra Portugal.jpg", "Monserrate Palace in Sintra.", "Monserrate Palace Sintra"),
  "Pena Palace": commonsImage("Pena Palace Sintra.jpg", "Colorful Pena Palace in Sintra.", "Pena Palace Sintra"),
  "National Palace of Sintra": commonsImage("Palácio Nacional de Sintra Portugal.jpg", "National Palace of Sintra.", "National Palace of Sintra"),
  "Óbidos": commonsImage("Obidos Portugal street.jpg", "Whitewashed streets in Obidos.", "Obidos Portugal"),
  "Nazaré": commonsImage("Nazaré Portugal beach.jpg", "Nazare beach and cliffs.", "Nazare Portugal"),
  Porto: commonsImage("Ribeira_Porto_Portugal.jpg", "Ribeira district in Porto.", "Porto Ribeira Portugal"),
  "São Bento Station": commonsImage("Estação de São Bento Porto.jpg", "Azulejo tiles in Sao Bento Station.", "Sao Bento Station Porto"),
  Ribeira: commonsImage("Ribeira_Porto_Portugal.jpg", "Ribeira waterfront in Porto.", "Ribeira Porto"),
  "Dom Luís I Bridge": commonsImage("Dom Luis I Bridge Porto Portugal.jpg", "Dom Luis I Bridge over the Douro.", "Dom Luis I Bridge Porto"),
  "Gaia cellar visit": commonsImage("Vila Nova de Gaia Porto wine cellars.jpg", "Port wine cellars in Vila Nova de Gaia.", "Vila Nova de Gaia wine cellars"),
  "Douro Valley tour": commonsImage("Douro Valley Portugal vineyards.jpg", "Vineyards in the Douro Valley.", "Douro Valley Portugal"),
  "Livraria Lello": commonsImage("Livraria Lello Porto Portugal.jpg", "Livraria Lello in Porto.", "Livraria Lello Porto"),
  "Clérigos Tower area": commonsImage("Torre dos Clérigos Porto.jpg", "Clerigos Tower in Porto.", "Clerigos Tower Porto"),
  "Crystal Palace Gardens": commonsImage("Jardins do Palácio de Cristal Porto.jpg", "Crystal Palace Gardens in Porto.", "Jardins Palacio de Cristal Porto"),
  "Foz do Douro sunset": commonsImage("Foz do Douro Porto Portugal.jpg", "Foz do Douro coastline in Porto.", "Foz do Douro Porto"),
};

export const portugalDayRouteSummaries: Record<number, string> = {
  1: "Overnight flight from Toronto to Lisbon.",
  2: "1 hr 8 mins, 9.5 mi. Lisbon arrival, hostel check-in, Belém classics, LX Factory, Time Out Market, Eduardo VII.",
  3: "1 hr 42 mins, 19.3 mi. Oceanário, Parque das Nações, castle, viewpoints, cathedral, Gulbenkian.",
  4: "1 hr 58 mins, 21.6 mi. Central Lisbon, Tile Museum, Graça, Tram 28, MAAT and bridge views.",
  5: "1 hr 41 mins, 12.6 mi. Ajuda, coach museum, Estrela, Ancient Art, Pink Street, Santo António night.",
  6: "Lisbon to Lagos transfer. Check out, train or bus south, check in, easy beach evening.",
  7: "1 hr 46 mins, 7.9 mi. Ponta da Piedade and Lagos beaches loop.",
  8: "Flex Algarve day: Seven Hanging Valleys / Benagil area or Sagres surf.",
  9: "Lagos to Lisbon transfer. Keep the evening light before Rachel lands.",
  10: "Rachel arrives in Lisbon. Coffee, bag drop, nap, soft catch-up day.",
  11: "Classic Lisbon together: Chiado, Carmo, Alfama, viewpoints, optional Fado dinner.",
  12: "Sintra day trip: Regaleira and Monserrate recommended; Pena if the iconic palace matters most.",
  13: "Driver day Lisbon to Porto with Óbidos and Nazaré stops. Arrive Porto late afternoon/evening.",
  14: "1 hr 56 mins, 122 mi. Porto anniversary-style day: São Bento, Ribeira, bridge, Gaia, dinner.",
  15: "Douro Valley full-day tour, roughly 8-10 hours with lunch, viewpoints, tastings, and river cruise.",
  16: "Final Porto day: Lello, Clérigos, Crystal Palace Gardens, Foz do Douro sunset.",
  17: "Porto to Toronto via Montreal. Flight day only.",
};

export const portugalRegionCalendar = [
  { startDay: 1, endDay: 1, region: "Flight" },
  { startDay: 2, endDay: 5, region: "Lisbon" },
  { startDay: 6, endDay: 8, region: "Lagos" },
  { startDay: 9, endDay: 11, region: "Lisbon" },
  { startDay: 12, endDay: 12, region: "Sintra" },
  { startDay: 13, endDay: 13, region: "Transfer" },
  { startDay: 14, endDay: 14, region: "Porto" },
  { startDay: 15, endDay: 15, region: "Douro Valley" },
  { startDay: 16, endDay: 17, region: "Porto" },
];

type SeedActivity = Omit<TripActivity, "id" | "tripId" | "country" | "currency" | "localCurrencyCode" | "attachmentIds" | "imageUrl" | "imageAlt" | "priority" | "isCompleted"> & {
  id?: string;
  latitude?: number;
  longitude?: number;
};

const cadToEur = (cad: number) => Number((cad * PORTUGAL_CAD_TO_EUR).toFixed(2));
const eurToCad = (eur: number) => Number((eur / PORTUGAL_CAD_TO_EUR).toFixed(2));

function activity(seed: SeedActivity): TripActivity {
  const image = portugalImageCatalog[seed.title] || portugalImageCatalog[seed.city];
  const localCost = seed.costLocal ?? seed.estimatedCost;
  return {
    id: seed.id || `portugal-${seed.day}-${seed.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    tripId: "portugal-2026",
    country: seed.city === "Toronto" || seed.city === "Montreal" ? "Canada" : seed.city === "Flight" ? "Canada" : "Portugal",
    currency: "EUR",
    localCurrencyCode: "EUR",
    attachmentIds: [],
    imageUrl: image?.imageUrl || scenic(seed.title),
    imageAlt: image?.imageAlt || `Generated visual for ${seed.title}.`,
    imageCredit: image?.imageCredit,
    imageCreditUrl: image?.imageCreditUrl,
    imageLicense: image?.imageLicense,
    imageSearchQuery: image?.imageSearchQuery || `${seed.title} ${seed.city} Portugal`,
    priority: seed.category === "Must See" || seed.category === "Non-Negotiable" ? 1 : seed.category === "Nice To Have" ? 2 : 3,
    isCompleted: false,
    ...seed,
    estimatedCost: localCost,
    costLocal: localCost,
    costCad: seed.costCad ?? eurToCad(localCost),
    needsConfirmationReasons: seed.needsConfirmationReasons || [],
  };
}

const portugalSeedActivities: SeedActivity[] = [
  {
    day: 1, date: "2026-06-08", city: "Toronto", region: "Flight", title: "Toronto to Lisbon",
    type: "flight", category: "Flight", description: "Overnight flight. Eat before boarding and try to sleep early.",
    address: "Toronto Pearson International Airport", googleMapsQuery: "Toronto Pearson International Airport", startTime: "21:30", endTime: "09:35",
    duration: "Overnight flight", travelTimeFromPrevious: "Start of trip", routeLegEstimate: "Start of trip", transportMode: "flight",
    estimatedCost: cadToEur(735.7), costCad: 735.7, costCategory: "flight", costStatus: "imported", bookingStatus: "booked",
    isBooked: true, notes: "Wanderlog: Air Transat TS 480, confirmation YPTTO3.", source: "Wanderlog PDF", sourceId: "TS480",
    latitude: 43.6777, longitude: -79.6248,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Lisbon", title: "We Hate F Tourists - Hostel",
    type: "hotel", category: "Hotel", description: "Solo Lisbon base. Check in, drop bags, keep the first day soft.",
    address: "R. Cap. Renato Baptista 88, 1150-043 Lisboa, Portugal", googleMapsQuery: "We Hate F Tourists Hostel Lisbon", duration: "Check in",
    travelTimeFromPrevious: "Flight arrives 9:35 AM", routeLegEstimate: "Flight arrives 9:35 AM", transportMode: "airport transfer",
    estimatedCost: 0, costCad: 0, costCategory: "hotel", costStatus: "imported", bookingStatus: "booked",
    isBooked: true, notes: "Booked lodging: €158.40, Jun 9-Jun 13.", source: "Wanderlog PDF", sourceId: "we-hate-f-tourists",
    latitude: 38.721, longitude: -9.139,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Belém", title: "Belém Tower",
    type: "activity", category: "Must See", description: "The classic Lisbon riverfront opener. Go for the setting even if interiors are not a priority.",
    address: "Av. Brasília, 1400-038 Lisboa, Portugal", googleMapsQuery: "Belém Tower Lisbon", duration: "30-45 min",
    travelTimeFromPrevious: "Arrive from hostel / airport", routeLegEstimate: "Arrive from hostel / airport", transportMode: "tram / taxi",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog says temporarily closed; treat as exterior/photo stop.", source: "Wanderlog PDF",
    latitude: 38.6916, longitude: -9.2160,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Belém", title: "Monument to the Discoveries",
    type: "activity", category: "Nice To Have", description: "Quick riverfront stop that pairs cleanly with Belém Tower and the monastery.",
    address: "Av. Brasília, 1400-038 Lisboa, Portugal", googleMapsQuery: "Padrão dos Descobrimentos Lisbon", duration: "20-40 min",
    travelTimeFromPrevious: "14 min · 0.71 mi", routeLegEstimate: "14 min · 0.71 mi", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-7PM.", source: "Wanderlog PDF",
    latitude: 38.6936, longitude: -9.2056,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Belém", title: "Pastéis de Belém",
    type: "food", category: "Food", description: "The obvious tart stop. Worth doing while you are already in Belém.",
    address: "R. de Belém 84 92, 1300-085 Lisboa, Portugal", googleMapsQuery: "Pastéis de Belém Lisbon", duration: "30 min",
    travelTimeFromPrevious: "10 min · 0.5 mi", routeLegEstimate: "10 min · 0.5 mi", transportMode: "walk",
    estimatedCost: 8, costCategory: "food", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: open 8AM-9PM.", source: "Wanderlog PDF",
    latitude: 38.6970, longitude: -9.2032,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Belém", title: "Jerónimos Monastery",
    type: "activity", category: "Must See", description: "The big Belém anchor. Do the exterior if energy is low after the flight.",
    address: "Praça do Império, 1400-206 Lisboa, Portugal", googleMapsQuery: "Jerónimos Monastery Lisbon", duration: "45-90 min",
    travelTimeFromPrevious: "3 min · 0.18 mi", routeLegEstimate: "3 min · 0.18 mi", transportMode: "walk",
    estimatedCost: 12, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 9:30AM-5:30PM.", source: "Wanderlog PDF",
    latitude: 38.6979, longitude: -9.2065,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Lisbon", title: "LX Factory",
    type: "activity", category: "Nice To Have", description: "A relaxed afternoon zone for shops, food, and not making the arrival day too formal.",
    address: "R. Rodrigues de Faria 103, 1300-501 Lisboa, Portugal", googleMapsQuery: "LX Factory Lisbon", duration: "1-2 hr",
    travelTimeFromPrevious: "4 min · 2.1 mi", routeLegEstimate: "4 min · 2.1 mi", transportMode: "ride / transit",
    estimatedCost: 15, costCategory: "food", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: open 10:30AM-10:30PM.", source: "Wanderlog PDF",
    latitude: 38.7028, longitude: -9.1785,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Lisbon", title: "Time Out Market",
    type: "food", category: "Food", description: "Easy food hall fallback when nobody wants to overthink dinner.",
    address: "Av. 24 de Julho 49, 1200-479 Lisboa, Portugal", googleMapsQuery: "Time Out Market Lisbon", duration: "45-75 min",
    travelTimeFromPrevious: "5 min · 2.3 mi", routeLegEstimate: "5 min · 2.3 mi", transportMode: "ride / transit",
    estimatedCost: 22, costCategory: "food", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog stop.", source: "Wanderlog PDF",
    latitude: 38.7072, longitude: -9.1445,
  },
  {
    day: 2, date: "2026-06-09", city: "Lisbon", region: "Lisbon", title: "Eduardo VII Park",
    type: "activity", category: "Extra", description: "A simple end-of-day viewpoint if there is still energy.",
    address: "Parque Eduardo VII, Lisboa, Portugal", googleMapsQuery: "Eduardo VII Park Lisbon", duration: "30 min",
    travelTimeFromPrevious: "8 min · 2.5 mi", routeLegEstimate: "8 min · 2.5 mi", transportMode: "ride / transit",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: scenic park and distant water views.", source: "Wanderlog PDF",
    latitude: 38.7283, longitude: -9.1503,
  },
  {
    day: 3, date: "2026-06-10", city: "Lisbon", region: "Parque das Nações", title: "Oceanário de Lisboa",
    type: "activity", category: "Nice To Have", description: "A strong rainy-day or low-pressure museum-style option.",
    address: "Esplanada Dom Carlos I, 1990-005 Lisboa, Portugal", googleMapsQuery: "Oceanário de Lisboa", duration: "1.5-2 hr",
    travelTimeFromPrevious: "12 min · 5.4 mi from hostel", routeLegEstimate: "12 min · 5.4 mi from hostel", transportMode: "metro / ride",
    estimatedCost: 25, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-7PM.", source: "Wanderlog PDF",
    latitude: 38.7636, longitude: -9.0936,
  },
  {
    day: 3, date: "2026-06-10", city: "Lisbon", region: "Parque das Nações", title: "Centro Vasco da Gama",
    type: "activity", category: "Extra", description: "Useful mall stop near the aquarium if weather turns or you need a practical break.",
    address: "Av. Dom João II 40, 1990-094 Lisboa, Portugal", googleMapsQuery: "Centro Vasco da Gama Lisbon", duration: "30-60 min",
    travelTimeFromPrevious: "13 min · 0.65 mi", routeLegEstimate: "13 min · 0.65 mi", transportMode: "walk",
    estimatedCost: 0, costCategory: "misc", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: open 8AM-12AM.", source: "Wanderlog PDF",
    latitude: 38.7677, longitude: -9.0956,
  },
  {
    day: 3, date: "2026-06-10", city: "Lisbon", region: "Alfama", title: "Castelo de São Jorge",
    type: "activity", category: "Must See", description: "Lisbon from above. Go for the views and old-city feeling.",
    address: "R. de Santa Cruz do Castelo, 1100-129 Lisboa, Portugal", googleMapsQuery: "Castelo de São Jorge Lisbon", duration: "1-1.5 hr",
    travelTimeFromPrevious: "12 min · 6.1 mi", routeLegEstimate: "12 min · 6.1 mi", transportMode: "ride / transit",
    estimatedCost: 15, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 9AM-9PM.", source: "Wanderlog PDF",
    latitude: 38.7139, longitude: -9.1335,
  },
  {
    day: 3, date: "2026-06-10", city: "Lisbon", region: "Alfama", title: "Miradouro da Senhora do Monte",
    type: "activity", category: "Must See", description: "One of the best Lisbon viewpoints. Worth saving a little energy for.",
    address: "Largo Monte, 1170-107 Lisboa, Portugal", googleMapsQuery: "Miradouro da Senhora do Monte Lisbon", duration: "20-30 min",
    travelTimeFromPrevious: "16 min · 0.81 mi", routeLegEstimate: "16 min · 0.81 mi", transportMode: "walk / ride",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: open 24 hours.", source: "Wanderlog PDF",
    latitude: 38.7190, longitude: -9.1328,
  },
  {
    day: 3, date: "2026-06-10", city: "Lisbon", region: "Alfama", title: "Miradouro de Santa Luzia",
    type: "activity", category: "Nice To Have", description: "A classic Alfama view with a softer, tiled Lisbon feel.",
    address: "Largo Santa Luzia, 1100-487 Lisboa, Portugal", googleMapsQuery: "Miradouro de Santa Luzia Lisbon", duration: "20 min",
    travelTimeFromPrevious: "14 min · 0.71 mi", routeLegEstimate: "14 min · 0.71 mi", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: open 24 hours.", source: "Wanderlog PDF",
    latitude: 38.7116, longitude: -9.1301,
  },
  {
    day: 3, date: "2026-06-10", city: "Lisbon", region: "Alfama", title: "Lisbon Cathedral",
    type: "activity", category: "Nice To Have", description: "Quick historic stop while already walking Alfama.",
    address: "Largo da Sé, 1100-585 Lisboa, Portugal", googleMapsQuery: "Lisbon Cathedral", duration: "25-45 min",
    travelTimeFromPrevious: "4 min · 0.22 mi", routeLegEstimate: "4 min · 0.22 mi", transportMode: "walk",
    estimatedCost: 5, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-6PM.", source: "Wanderlog PDF",
    latitude: 38.7098, longitude: -9.1335,
  },
  {
    day: 3, date: "2026-06-10", city: "Lisbon", region: "Lisbon", title: "Calouste Gulbenkian Museum",
    type: "activity", category: "Nice To Have", description: "A calmer museum option if the city walking starts feeling like too much.",
    address: "Av. de Berna 45A, 1067-001 Lisboa, Portugal", googleMapsQuery: "Calouste Gulbenkian Museum Lisbon", duration: "1.5-2 hr",
    travelTimeFromPrevious: "6 min · 2 mi from viewpoint route", routeLegEstimate: "6 min · 2 mi from viewpoint route", transportMode: "ride / metro",
    estimatedCost: 15, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-6PM.", source: "Wanderlog PDF",
    latitude: 38.7371, longitude: -9.1547,
  },
  {
    day: 4, date: "2026-06-11", city: "Lisbon", region: "Baixa", title: "Santa Justa Lift",
    type: "activity", category: "Extra", description: "See it from outside unless the line is tiny.",
    address: "R. do Ouro, 1150-060 Lisboa, Portugal", googleMapsQuery: "Santa Justa Lift Lisbon", duration: "15-30 min",
    travelTimeFromPrevious: "17 min · 0.87 mi from hostel", routeLegEstimate: "17 min · 0.87 mi from hostel", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog says temporarily closed.", source: "Wanderlog PDF",
    latitude: 38.7121, longitude: -9.1394,
  },
  {
    day: 4, date: "2026-06-11", city: "Lisbon", region: "Baixa", title: "Rua Augusta Arch",
    type: "activity", category: "Nice To Have", description: "A quick city-center landmark with Praça do Comércio right there.",
    address: "R. Augusta 2, 1100-053 Lisboa, Portugal", googleMapsQuery: "Rua Augusta Arch Lisbon", duration: "20-40 min",
    travelTimeFromPrevious: "7 min · 0.34 mi", routeLegEstimate: "7 min · 0.34 mi", transportMode: "walk",
    estimatedCost: 4, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-7PM.", source: "Wanderlog PDF",
    latitude: 38.7080, longitude: -9.1367,
  },
  {
    day: 4, date: "2026-06-11", city: "Lisbon", region: "Lisbon", title: "Museu Nacional do Azulejo",
    type: "activity", category: "Nice To Have", description: "Tiles are Portugal’s visual language; this is the focused version.",
    address: "R. Me. Deus 4, 1900-312 Lisboa, Portugal", googleMapsQuery: "Museu Nacional do Azulejo Lisbon", duration: "1-1.5 hr",
    travelTimeFromPrevious: "5 min · 2.3 mi", routeLegEstimate: "5 min · 2.3 mi", transportMode: "ride",
    estimatedCost: 8, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog says temporarily closed; confirm before going.", source: "Wanderlog PDF",
    latitude: 38.7244, longitude: -9.1139,
  },
  {
    day: 4, date: "2026-06-11", city: "Lisbon", region: "Graça", title: "National Pantheon",
    type: "activity", category: "Nice To Have", description: "Good architecture stop before the Graça viewpoint.",
    address: "Campo de Santa Clara, 1100-471 Lisboa, Portugal", googleMapsQuery: "National Pantheon Lisbon", duration: "45-60 min",
    travelTimeFromPrevious: "20 min · 1 mi", routeLegEstimate: "20 min · 1 mi", transportMode: "walk / ride",
    estimatedCost: 8, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-5PM.", source: "Wanderlog PDF",
    latitude: 38.7149, longitude: -9.1249,
  },
  {
    day: 4, date: "2026-06-11", city: "Lisbon", region: "Graça", title: "Tram 28",
    type: "transport", category: "Transit", description: "Do a short tram experience, not a whole tourist endurance test.",
    address: "Lisbon, Portugal", googleMapsQuery: "Tram 28 Lisbon", duration: "20-40 min",
    travelTimeFromPrevious: "8 min · 0.43 mi from Graça", routeLegEstimate: "8 min · 0.43 mi from Graça", transportMode: "tram",
    estimatedCost: 4, costCategory: "transport", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog tram stop.", source: "Wanderlog PDF",
    latitude: 38.7168, longitude: -9.1311,
  },
  {
    day: 4, date: "2026-06-11", city: "Lisbon", region: "Belém", title: "MAAT - Museum of Art, Architecture and Technology",
    type: "activity", category: "Extra", description: "Riverside museum option if you want a design/architecture break.",
    address: "Av. Brasília, 1300-598 Lisboa, Portugal", googleMapsQuery: "MAAT Lisbon", duration: "1 hr",
    travelTimeFromPrevious: "19 min · 0.97 mi from bridge area", routeLegEstimate: "19 min · 0.97 mi from bridge area", transportMode: "ride",
    estimatedCost: 12, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-7PM.", source: "Wanderlog PDF",
    latitude: 38.6960, longitude: -9.1944,
  },
  {
    day: 5, date: "2026-06-12", city: "Lisbon", region: "Lisbon", title: "Palácio Nacional da Ajuda",
    type: "activity", category: "Nice To Have", description: "Palace interiors without needing to leave Lisbon.",
    address: "Largo da Ajuda, 1349-021 Lisboa, Portugal", googleMapsQuery: "Palácio Nacional da Ajuda Lisbon", duration: "1-1.5 hr",
    travelTimeFromPrevious: "13 min · 5.5 mi from hostel", routeLegEstimate: "13 min · 5.5 mi from hostel", transportMode: "ride / transit",
    estimatedCost: 12, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 10AM-6PM.", source: "Wanderlog PDF",
    latitude: 38.7074, longitude: -9.1988,
  },
  {
    day: 5, date: "2026-06-12", city: "Lisbon", region: "Lisbon", title: "Basilica of Estrela",
    type: "activity", category: "Extra", description: "A compact stop with a beautiful neighborhood feel.",
    address: "Praça da Estrela, 1200-667 Lisboa, Portugal", googleMapsQuery: "Basilica of Estrela Lisbon", duration: "30-45 min",
    travelTimeFromPrevious: "6 min · 2.9 mi from Coach Museum", routeLegEstimate: "6 min · 2.9 mi from Coach Museum", transportMode: "ride",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 9AM-7:45PM.", source: "Wanderlog PDF",
    latitude: 38.7149, longitude: -9.1599,
  },
  {
    day: 5, date: "2026-06-12", city: "Lisbon", region: "Lisbon", title: "Pink Street",
    type: "activity", category: "Extra", description: "Easy evening atmosphere before Santo António crowds.",
    address: "R. Nova do Carvalho, 1200-161 Lisboa, Portugal", googleMapsQuery: "Pink Street Lisbon", duration: "30-60 min",
    travelTimeFromPrevious: "20 min · 1 mi from museum route", routeLegEstimate: "20 min · 1 mi from museum route", transportMode: "walk / ride",
    estimatedCost: 15, costCategory: "food", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog stop.", source: "Wanderlog PDF",
    latitude: 38.7067, longitude: -9.1437,
  },
  {
    day: 5, date: "2026-06-12", city: "Lisbon", region: "Alfama", title: "Santo António festival night",
    type: "activity", category: "Non-Negotiable", description: "This is the Lisbon night: streets, music, crowds, and grilled sardine energy.",
    address: "Alfama, Lisbon, Portugal", googleMapsQuery: "Santo Antonio festival Alfama Lisbon", duration: "Evening",
    travelTimeFromPrevious: "Local walking/transit", routeLegEstimate: "Local walking/transit", transportMode: "walk / transit",
    estimatedCost: 30, costCategory: "food", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Google Doc PDF: do not schedule an early departure next day; pick a meetup spot before crowds.", source: "Google Doc PDF",
    latitude: 38.7111, longitude: -9.1305,
  },
  {
    day: 6, date: "2026-06-13", city: "Lagos", region: "Algarve", title: "Lisbon to Lagos",
    type: "transport", category: "Transit", description: "Late morning or early afternoon train/bus south. Avoid a brutal start after festival night.",
    address: "Lagos, Portugal", googleMapsQuery: "Lisbon to Lagos Portugal train bus", duration: "3h50-4h15",
    travelTimeFromPrevious: "3h50-4h15 from Lisbon", routeLegEstimate: "3h50-4h15 from Lisbon", transportMode: "train / bus",
    estimatedCost: 35, costCategory: "transport", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: book Lagos to Lisbon return too; arrive back before 8PM on Jun 16.", source: "Google Doc PDF",
    latitude: 37.1028, longitude: -8.6742,
  },
  {
    day: 6, date: "2026-06-13", city: "Lagos", region: "Algarve", title: "Sol a Sol Hostel",
    type: "hotel", category: "Hotel", description: "Solo Lagos base for beach and hostel social nights.",
    address: "R. Lançarote de Freitas 22, 8600-605 Lagos, Portugal", googleMapsQuery: "Sol a Sol Hostel Lagos Portugal", duration: "Check in",
    travelTimeFromPrevious: "After Lisbon to Lagos transfer", routeLegEstimate: "After Lisbon to Lagos transfer", transportMode: "walk / taxi",
    estimatedCost: 0, costCategory: "hotel", costStatus: "imported", bookingStatus: "booked", isBooked: true, notes: "Booked lodging: €105.00, Jun 13-Jun 16.", source: "Wanderlog PDF",
    latitude: 37.1018, longitude: -8.6736,
  },
  {
    day: 7, date: "2026-06-14", city: "Lagos", region: "Algarve", title: "Ponta da Piedade",
    type: "activity", category: "Must See", description: "The Lagos coastline moment. Morning is best if doing kayak or boat.",
    address: "Ponta da Piedade, Lagos, Portugal", googleMapsQuery: "Ponta da Piedade Lagos", duration: "1.5-2 hr",
    travelTimeFromPrevious: "4 min · 1.4 mi from hostel", routeLegEstimate: "4 min · 1.4 mi from hostel", transportMode: "walk / taxi",
    estimatedCost: 40, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Book kayak or boat for Sunday morning. Kayak often CAD 50-60; boat often CAD 30-45.", source: "Wanderlog PDF",
    latitude: 37.0820, longitude: -8.6684,
  },
  {
    day: 7, date: "2026-06-14", city: "Lagos", region: "Algarve", title: "Praia do Camilo",
    type: "activity", category: "Nice To Have", description: "Pretty beach stop right after Ponta da Piedade.",
    address: "Praia do Camilo, Lagos, Portugal", googleMapsQuery: "Praia do Camilo Lagos", duration: "45-90 min",
    travelTimeFromPrevious: "14 min · 0.68 mi", routeLegEstimate: "14 min · 0.68 mi", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog beach stop.", source: "Wanderlog PDF",
    latitude: 37.0882, longitude: -8.6690,
  },
  {
    day: 7, date: "2026-06-14", city: "Lagos", region: "Algarve", title: "Praia Dona Ana",
    type: "activity", category: "Nice To Have", description: "Another easy beach in the same coastline loop.",
    address: "Praia Dona Ana, Lagos, Portugal", googleMapsQuery: "Praia Dona Ana Lagos", duration: "45-90 min",
    travelTimeFromPrevious: "14 min · 0.72 mi", routeLegEstimate: "14 min · 0.72 mi", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: open 24 hours.", source: "Wanderlog PDF",
    latitude: 37.0915, longitude: -8.6694,
  },
  {
    day: 7, date: "2026-06-14", city: "Lagos", region: "Algarve", title: "Restaurante The Garden",
    type: "food", category: "Food", description: "Casual food break after the beach loop.",
    address: "Lagos, Portugal", googleMapsQuery: "Restaurante The Garden Lagos Portugal", duration: "60-90 min",
    travelTimeFromPrevious: "13 min · 0.65 mi", routeLegEstimate: "13 min · 0.65 mi", transportMode: "walk",
    estimatedCost: 28, costCategory: "food", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Wanderlog: open 12-11PM.", source: "Wanderlog PDF",
    latitude: 37.1027, longitude: -8.6754,
  },
  {
    day: 7, date: "2026-06-14", city: "Lagos", region: "Algarve", title: "Beach Estudantes",
    type: "activity", category: "Extra", description: "Small scenic cove, good as a low-effort filler.",
    address: "Praia dos Estudantes, Lagos, Portugal", googleMapsQuery: "Praia dos Estudantes Lagos", duration: "30-60 min",
    travelTimeFromPrevious: "8 min · 0.39 mi from Praia do Pinhão", routeLegEstimate: "8 min · 0.39 mi from Praia do Pinhão", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog beach stop.", source: "Wanderlog PDF",
    latitude: 37.0964, longitude: -8.6698,
  },
  {
    day: 8, date: "2026-06-15", city: "Algarve", region: "Algarve", title: "Seven Hanging Valleys hike",
    type: "activity", category: "Nice To Have", description: "Pick this if you want cliffs and a cheaper self-guided adventure day.",
    address: "Seven Hanging Valleys Trail, Algarve, Portugal", googleMapsQuery: "Seven Hanging Valleys Trail Algarve", duration: "Half day",
    travelTimeFromPrevious: "Depends on transport", routeLegEstimate: "Depends on transport", transportMode: "tour / bus / ride",
    estimatedCost: 65, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Google Doc PDF: choose this OR beginner surf day, not both.", source: "Google Doc PDF",
    latitude: 37.0919, longitude: -8.4531,
  },
  {
    day: 8, date: "2026-06-15", city: "Sagres", region: "Algarve", title: "Sagres surf option",
    type: "activity", category: "Extra", description: "More social and active than the hike. Choose this if you want a surf day.",
    address: "Sagres, Portugal", googleMapsQuery: "beginner surf Sagres Portugal", duration: "Half day",
    travelTimeFromPrevious: "Depends on activity", routeLegEstimate: "Depends on activity", transportMode: "tour / shuttle",
    estimatedCost: 85, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Google Doc PDF: beginner surf day often CAD 70-130.", source: "Google Doc PDF",
    latitude: 37.0079, longitude: -8.9478,
  },
  {
    day: 9, date: "2026-06-16", city: "Lisbon", region: "Transfer", title: "Lagos to Lisbon",
    type: "transport", category: "Transit", description: "Slow Lagos morning, then return to Lisbon before Rachel lands the next day.",
    address: "Lisbon, Portugal", googleMapsQuery: "Lagos to Lisbon train bus", duration: "3h50-4h15",
    travelTimeFromPrevious: "3h50-4h15 from Lagos", routeLegEstimate: "3h50-4h15 from Lagos", transportMode: "train / bus",
    estimatedCost: 35, costCategory: "transport", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: aim to arrive before 8PM.", source: "Google Doc PDF",
    latitude: 38.7223, longitude: -9.1393,
  },
  {
    day: 10, date: "2026-06-17", city: "Lisbon", region: "Lisbon", title: "Rachel arrives in Lisbon",
    type: "flight", category: "Flight", description: "Airport pickup, coffee, bag drop, nap, and a low-key dinner.",
    address: "Humberto Delgado Airport, Lisbon, Portugal", googleMapsQuery: "Lisbon Airport", startTime: "06:30", duration: "Arrival morning",
    travelTimeFromPrevious: "Montreal to Lisbon arrives 6:30 AM", routeLegEstimate: "Montreal to Lisbon arrives 6:30 AM", transportMode: "flight",
    estimatedCost: cadToEur(727.87), costCad: 727.87, costCategory: "flight", costStatus: "imported", bookingStatus: "booked", isBooked: true, notes: "Wanderlog: YTZ-YUL TS7463, YUL-LIS TS680, confirmation AO742L.", source: "Wanderlog PDF",
    latitude: 38.7742, longitude: -9.1342,
  },
  {
    day: 10, date: "2026-06-17", city: "Lisbon", region: "Lisbon", title: "Hostel Green Heart",
    type: "hotel", category: "Hotel", description: "Together Lisbon base after Rachel lands.",
    address: "R. de Santa Marta 37, 1150-293 Lisboa, Portugal", googleMapsQuery: "Hostel Green Heart Lisbon", duration: "Check in",
    travelTimeFromPrevious: "Airport pickup and bag drop", routeLegEstimate: "Airport pickup and bag drop", transportMode: "taxi / metro",
    estimatedCost: 0, costCategory: "hotel", costStatus: "imported", bookingStatus: "booked", isBooked: true, notes: "Booked lodging: €256.50, Jun 17-Jun 20.", source: "Wanderlog PDF",
    latitude: 38.7255, longitude: -9.1457,
  },
  {
    day: 11, date: "2026-06-18", city: "Lisbon", region: "Lisbon", title: "Carmo Convent and Chiado",
    type: "activity", category: "Nice To Have", description: "Classic Lisbon together without making the day too packed.",
    address: "Largo do Carmo, 1200-092 Lisboa, Portugal", googleMapsQuery: "Carmo Convent Lisbon", duration: "1-2 hr",
    travelTimeFromPrevious: "Local transit/walking", routeLegEstimate: "Local transit/walking", transportMode: "walk / tram",
    estimatedCost: 12, costCategory: "activity", costStatus: "manual", bookingStatus: "optional", isBooked: false, notes: "Google Doc PDF: optional Fado dinner if not too tired.", source: "Google Doc PDF",
    latitude: 38.7111, longitude: -9.1403,
  },
  {
    day: 11, date: "2026-06-18", city: "Lisbon", region: "Alfama", title: "Alfama viewpoints together",
    type: "activity", category: "Must See", description: "Slow stairs, views, and the part of Lisbon that feels most like wandering.",
    address: "Alfama, Lisbon, Portugal", googleMapsQuery: "Alfama Lisbon viewpoints", duration: "2 hr",
    travelTimeFromPrevious: "Walking / tram", routeLegEstimate: "Walking / tram", transportMode: "walk / tram",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Google Doc PDF: Senhora do Monte or Santa Luzia.", source: "Google Doc PDF",
    latitude: 38.7114, longitude: -9.1300,
  },
  {
    day: 12, date: "2026-06-19", city: "Sintra", region: "Sintra", title: "Quinta da Regaleira",
    type: "activity", category: "Must See", description: "The recommended Sintra anchor: atmospheric, strange, and better paced as a couple.",
    address: "R. Barbosa du Bocage 5, 2710-567 Sintra, Portugal", googleMapsQuery: "Quinta da Regaleira Sintra", duration: "1.5-2 hr",
    travelTimeFromPrevious: "40 min train from Lisbon + local transfers", routeLegEstimate: "40 min train from Lisbon + local transfers", transportMode: "train / local transfer",
    estimatedCost: 20, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: official adult price listed as EUR 20, approx CAD 32.", source: "Google Doc PDF",
    latitude: 38.7966, longitude: -9.4633,
  },
  {
    day: 12, date: "2026-06-19", city: "Sintra", region: "Sintra", title: "Monserrate Palace",
    type: "activity", category: "Nice To Have", description: "Calmer gardens and better pacing than trying to do every Sintra icon.",
    address: "2710-405 Sintra, Portugal", googleMapsQuery: "Monserrate Palace Sintra", duration: "1.5-2 hr",
    travelTimeFromPrevious: "Local transfer from Regaleira", routeLegEstimate: "Local transfer from Regaleira", transportMode: "bus / tuk tuk / taxi",
    estimatedCost: 12, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: recommended with Regaleira; official adult price listed as EUR 12.", source: "Google Doc PDF",
    latitude: 38.7939, longitude: -9.4219,
  },
  {
    day: 12, date: "2026-06-19", city: "Sintra", region: "Sintra", title: "Pena Palace",
    type: "activity", category: "Extra", description: "The famous colorful palace. Add only if iconic beats calm.",
    address: "Estrada da Pena, 2710-609 Sintra, Portugal", googleMapsQuery: "Pena Palace Sintra", duration: "1.5-2 hr",
    travelTimeFromPrevious: "Local transfer", routeLegEstimate: "Local transfer", transportMode: "bus / shuttle",
    estimatedCost: 20, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: timed entry required; optional shuttle around CAD 7.", source: "Google Doc PDF",
    latitude: 38.7876, longitude: -9.3906,
  },
  {
    day: 13, date: "2026-06-20", city: "Óbidos", region: "Transfer", title: "Óbidos",
    type: "activity", category: "Nice To Have", description: "First scenic stop on the driver day north.",
    address: "Óbidos, Portugal", googleMapsQuery: "Óbidos Portugal", duration: "60-90 min",
    travelTimeFromPrevious: "Driver day from Lisbon", routeLegEstimate: "Driver day from Lisbon", transportMode: "driver",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: confirm luggage before booking transfer.", source: "Google Doc PDF",
    latitude: 39.3609, longitude: -9.1560,
  },
  {
    day: 13, date: "2026-06-20", city: "Nazaré", region: "Transfer", title: "Nazaré",
    type: "activity", category: "Nice To Have", description: "Coastal stop on the way to Porto. Keep it simple so the transfer does not sprawl.",
    address: "Nazaré, Portugal", googleMapsQuery: "Nazaré Portugal", duration: "60-90 min",
    travelTimeFromPrevious: "Driver day stop after Óbidos", routeLegEstimate: "Driver day stop after Óbidos", transportMode: "driver",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: limit the driver day to around two main places.", source: "Google Doc PDF",
    latitude: 39.6029, longitude: -9.0702,
  },
  {
    day: 13, date: "2026-06-20", city: "Porto", region: "Porto", title: "Caruma Surf Hostel",
    type: "hotel", category: "Hotel", description: "Porto/Matosinhos base for the final stretch.",
    address: "R. Brito e Cunha 413, 4450-189 Matosinhos, Portugal", googleMapsQuery: "Caruma Surf Hostel Matosinhos Porto", duration: "Check in",
    travelTimeFromPrevious: "Arrive Porto late afternoon/evening", routeLegEstimate: "Arrive Porto late afternoon/evening", transportMode: "driver",
    estimatedCost: 0, costCategory: "hotel", costStatus: "imported", bookingStatus: "booked", isBooked: true, notes: "Booked lodging: €310.48, Jun 20-Jun 24.", source: "Wanderlog PDF",
    latitude: 41.1836, longitude: -8.6876,
  },
  {
    day: 14, date: "2026-06-21", city: "Porto", region: "Porto", title: "São Bento Station",
    type: "activity", category: "Must See", description: "Tiles, station energy, and an easy start to the Porto walking day.",
    address: "Praça de Almeida Garrett, 4000-069 Porto, Portugal", googleMapsQuery: "São Bento Station Porto", duration: "20-30 min",
    travelTimeFromPrevious: "Walking/short ride", routeLegEstimate: "Walking/short ride", transportMode: "walk / metro",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Google Doc PDF anniversary-style day.", source: "Google Doc PDF",
    latitude: 41.1457, longitude: -8.6109,
  },
  {
    day: 14, date: "2026-06-21", city: "Porto", region: "Porto", title: "Ribeira",
    type: "activity", category: "Must See", description: "Riverfront Porto. Go for atmosphere more than a checklist.",
    address: "Ribeira, Porto, Portugal", googleMapsQuery: "Ribeira Porto Portugal", duration: "60-90 min",
    travelTimeFromPrevious: "Short walk from São Bento", routeLegEstimate: "Short walk from São Bento", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Wanderlog: historic Porto day.", source: "Wanderlog PDF",
    latitude: 41.1406, longitude: -8.6110,
  },
  {
    day: 14, date: "2026-06-21", city: "Porto", region: "Porto", title: "Dom Luís I Bridge",
    type: "activity", category: "Must See", description: "The Porto crossing. Views do most of the work here.",
    address: "Ponte de Dom Luís I, Porto, Portugal", googleMapsQuery: "Dom Luís I Bridge Porto", duration: "30-45 min",
    travelTimeFromPrevious: "Walk from Ribeira", routeLegEstimate: "Walk from Ribeira", transportMode: "walk",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Google Doc PDF: bridge and Gaia riverfront.", source: "Google Doc PDF",
    latitude: 41.1402, longitude: -8.6096,
  },
  {
    day: 14, date: "2026-06-21", city: "Vila Nova de Gaia", region: "Porto", title: "Gaia cellar visit",
    type: "activity", category: "Nice To Have", description: "Choose a history/scenic version so it works even without making wine the whole point.",
    address: "Vila Nova de Gaia, Portugal", googleMapsQuery: "Vila Nova de Gaia cellar history visit", duration: "1-2 hr",
    travelTimeFromPrevious: "Walk across bridge", routeLegEstimate: "Walk across bridge", transportMode: "walk",
    estimatedCost: 45, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: CAD 20-80 depending on provider.", source: "Google Doc PDF",
    latitude: 41.1336, longitude: -8.6136,
  },
  {
    day: 15, date: "2026-06-22", city: "Douro Valley", region: "Douro Valley", title: "Douro Valley tour",
    type: "activity", category: "Non-Negotiable", description: "Long scenic day with lunch, viewpoints, river cruise, and a quinta/village stop.",
    address: "Douro Valley, Portugal", googleMapsQuery: "Douro Valley day tour Porto lunch river cruise", duration: "8-10 hr",
    travelTimeFromPrevious: "58 min · 60 mi from Porto", routeLegEstimate: "58 min · 60 mi from Porto", transportMode: "tour / driver",
    estimatedCost: cadToEur(289.06), costCad: 289.06, costCategory: "activity", costStatus: "imported", bookingStatus: "booked", isBooked: true, notes: "Wanderlog expenses: Day tour gyg CA$289.06. Google Doc PDF says keep dinner simple after.", source: "Wanderlog PDF",
    latitude: 41.1621, longitude: -7.7716,
  },
  {
    day: 16, date: "2026-06-23", city: "Porto", region: "Porto", title: "Livraria Lello",
    type: "activity", category: "Nice To Have", description: "Book timed entry and go early or late if you care about seeing it without stress.",
    address: "R. das Carmelitas 144, 4050-161 Porto, Portugal", googleMapsQuery: "Livraria Lello Porto", duration: "45-60 min",
    travelTimeFromPrevious: "Walking/metro/taxi", routeLegEstimate: "Walking/metro/taxi", transportMode: "walk / metro",
    estimatedCost: 10, costCategory: "activity", costStatus: "manual", bookingStatus: "needs-confirmation", isBooked: false, notes: "Google Doc PDF: tickets start around EUR 10, approx CAD 16.", source: "Google Doc PDF",
    latitude: 41.1469, longitude: -8.6148,
  },
  {
    day: 16, date: "2026-06-23", city: "Porto", region: "Porto", title: "Crystal Palace Gardens",
    type: "activity", category: "Nice To Have", description: "A slower final-day stop with views and space to breathe.",
    address: "R. de Dom Manuel II, 4050-346 Porto, Portugal", googleMapsQuery: "Jardins do Palácio de Cristal Porto", duration: "45-90 min",
    travelTimeFromPrevious: "Short ride/walk from Lello", routeLegEstimate: "Short ride/walk from Lello", transportMode: "walk / ride",
    estimatedCost: 0, costCategory: "activity", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Google Doc PDF: great slower final-day activity.", source: "Google Doc PDF",
    latitude: 41.1483, longitude: -8.6256,
  },
  {
    day: 16, date: "2026-06-23", city: "Porto", region: "Porto", title: "Foz do Douro sunset",
    type: "activity", category: "Must See", description: "Final sunset plan. Keep it flexible and let the day end near the water.",
    address: "Foz do Douro, Porto, Portugal", googleMapsQuery: "Foz do Douro Porto sunset", duration: "1-2 hr",
    travelTimeFromPrevious: "Transit/ride cost from city center", routeLegEstimate: "Transit/ride cost from city center", transportMode: "tram / ride",
    estimatedCost: 8, costCategory: "transport", costStatus: "manual", bookingStatus: "not-booked", isBooked: false, notes: "Google Doc PDF: best final sunset plan.", source: "Google Doc PDF",
    latitude: 41.1528, longitude: -8.6718,
  },
  {
    day: 17, date: "2026-06-24", city: "Porto", region: "Flight", title: "Porto to Toronto",
    type: "flight", category: "Flight", description: "Breakfast, airport transfer, then flight home via Montreal.",
    address: "Francisco Sá Carneiro Airport, Porto, Portugal", googleMapsQuery: "Porto Airport", startTime: "08:25", endTime: "14:15",
    duration: "Flight day", travelTimeFromPrevious: "Airport transfer", routeLegEstimate: "Airport transfer", transportMode: "flight",
    estimatedCost: 0, costCad: 0, costCategory: "flight", costStatus: "needs-confirmation", bookingStatus: "booked", isBooked: true, notes: "Wanderlog: Air Transat TS 175 OPO-YUL, then TS 7320 YUL-YTZ. Google Doc had older 1:30 PM note; Wanderlog flight section is used here.", source: "Wanderlog PDF",
    latitude: 41.2481, longitude: -8.6814,
  },
];

export const portugalActivities: TripActivity[] = portugalSeedActivities.map(activity);

export const portugalFlights: TripFlight[] = [
  {
    id: "portugal-flight-ts480",
    tripId: "portugal-2026",
    airline: "Air Transat",
    flightNumber: "TS 480",
    departureAirport: "Toronto Pearson International Airport (YYZ)",
    arrivalAirport: "Lisbon Airport (LIS)",
    departureTime: "2026-06-08T21:30:00",
    arrivalTime: "2026-06-09T09:35:00",
    confirmation: "YPTTO3",
    status: "booked",
    notes: "Imported from Wanderlog flight section.",
    costCad: 735.7,
    costLocal: cadToEur(735.7),
    localCurrencyCode: "EUR",
    source: "Wanderlog PDF",
    sourceId: "TS480",
  },
  {
    id: "portugal-flight-ts7463",
    tripId: "portugal-2026",
    airline: "Air Transat",
    flightNumber: "TS 7463",
    departureAirport: "Billy Bishop Toronto City Airport (YTZ)",
    arrivalAirport: "Montreal (YUL)",
    departureTime: "2026-06-16T16:00:00",
    arrivalTime: "2026-06-16T17:15:00",
    confirmation: "AO742L",
    status: "booked",
    notes: "Rachel outbound first leg. Imported from Wanderlog.",
    costCad: 727.87,
    costLocal: cadToEur(727.87),
    localCurrencyCode: "EUR",
    source: "Wanderlog PDF",
    sourceId: "TS7463",
  },
  {
    id: "portugal-flight-ts680",
    tripId: "portugal-2026",
    airline: "Air Transat",
    flightNumber: "TS 680",
    departureAirport: "Montreal (YUL)",
    arrivalAirport: "Lisbon Airport (LIS)",
    departureTime: "2026-06-16T19:00:00",
    arrivalTime: "2026-06-17T06:30:00",
    confirmation: "AO742L",
    status: "booked",
    notes: "Rachel outbound second leg. Plan airport transit.",
    costCad: 0,
    costLocal: 0,
    localCurrencyCode: "EUR",
    source: "Wanderlog PDF",
    sourceId: "TS680",
  },
  {
    id: "portugal-flight-ts175",
    tripId: "portugal-2026",
    airline: "Air Transat",
    flightNumber: "TS 175",
    departureAirport: "Porto Airport (OPO)",
    arrivalAirport: "Montreal (YUL)",
    departureTime: "2026-06-24T08:25:00",
    arrivalTime: "2026-06-24T10:40:00",
    confirmation: "",
    status: "booked",
    notes: "Return first leg. Wanderlog timing used.",
    costCad: 0,
    costLocal: 0,
    localCurrencyCode: "EUR",
    source: "Wanderlog PDF",
    sourceId: "TS175",
  },
  {
    id: "portugal-flight-ts7320",
    tripId: "portugal-2026",
    airline: "Air Transat",
    flightNumber: "TS 7320",
    departureAirport: "Montreal (YUL)",
    arrivalAirport: "Billy Bishop Toronto City Airport (YTZ)",
    departureTime: "2026-06-24T12:50:00",
    arrivalTime: "2026-06-24T14:15:00",
    confirmation: "",
    status: "booked",
    notes: "Return second leg. Exact return cost not in the PDF.",
    costCad: 0,
    costLocal: 0,
    localCurrencyCode: "EUR",
    source: "Wanderlog PDF",
    sourceId: "TS7320",
  },
];

export const portugalHotels: TripHotel[] = [
  {
    id: "portugal-hotel-we-hate-f-tourists",
    tripId: "portugal-2026",
    name: "We Hate F Tourists - Hostel",
    city: "Lisbon",
    country: "Portugal",
    address: "R. Cap. Renato Baptista 88, 1150-043 Lisboa, Portugal",
    checkIn: "2026-06-09",
    checkOut: "2026-06-13",
    estimatedCost: 158.4,
    currency: "EUR",
    costLocal: 158.4,
    localCurrencyCode: "EUR",
    costCad: eurToCad(158.4),
    costStatus: "imported",
    source: "Wanderlog PDF",
    sourceId: "we-hate-f-tourists",
    notes: "Booked solo Lisbon lodging.",
    latitude: 38.721,
    longitude: -9.139,
  },
  {
    id: "portugal-hotel-sol-a-sol",
    tripId: "portugal-2026",
    name: "Sol a Sol Hostel",
    city: "Lagos",
    country: "Portugal",
    address: "R. Lançarote de Freitas 22, 8600-605 Lagos, Portugal",
    checkIn: "2026-06-13",
    checkOut: "2026-06-16",
    estimatedCost: 105,
    currency: "EUR",
    costLocal: 105,
    localCurrencyCode: "EUR",
    costCad: eurToCad(105),
    costStatus: "imported",
    source: "Wanderlog PDF",
    sourceId: "sol-a-sol",
    notes: "Booked solo Lagos lodging.",
    latitude: 37.1018,
    longitude: -8.6736,
  },
  {
    id: "portugal-hotel-green-heart",
    tripId: "portugal-2026",
    name: "Hostel Green Heart",
    city: "Lisbon",
    country: "Portugal",
    address: "R. de Santa Marta 37, 1150-293 Lisboa, Portugal",
    checkIn: "2026-06-17",
    checkOut: "2026-06-20",
    estimatedCost: 256.5,
    currency: "EUR",
    costLocal: 256.5,
    localCurrencyCode: "EUR",
    costCad: eurToCad(256.5),
    costStatus: "imported",
    source: "Wanderlog PDF",
    sourceId: "green-heart",
    notes: "Booked Lisbon lodging together.",
    latitude: 38.7255,
    longitude: -9.1457,
  },
  {
    id: "portugal-hotel-caruma",
    tripId: "portugal-2026",
    name: "Caruma Surf Hostel",
    city: "Porto",
    country: "Portugal",
    address: "R. Brito e Cunha 413, 4450-189 Matosinhos, Portugal",
    checkIn: "2026-06-20",
    checkOut: "2026-06-24",
    estimatedCost: 310.48,
    currency: "EUR",
    costLocal: 310.48,
    localCurrencyCode: "EUR",
    costCad: eurToCad(310.48),
    costStatus: "imported",
    source: "Wanderlog PDF",
    sourceId: "caruma",
    notes: "Booked Porto/Matosinhos lodging.",
    latitude: 41.1836,
    longitude: -8.6876,
  },
];

export const portugalAttachments: TripAttachment[] = [
  {
    id: "portugal-google-doc-pdf-source",
    tripId: "portugal-2026",
    fileName: "Portugal_Mainland_Trip_Itinerary_June_2026.docx.pdf",
    type: "pdf",
    note: "Google Docs itinerary PDF used for route overview, pacing notes, optional activities, booking checklist, packing list, and travel tips.",
    localReference: PORTUGAL_GOOGLE_DOC_PDF_SOURCE,
    isSensitivePlaceholder: false,
  },
  {
    id: "portugal-wanderlog-pdf-source",
    tripId: "portugal-2026",
    fileName: "Trip to Portugal – Wanderlog.pdf",
    type: "pdf",
    note: "Wanderlog PDF used for booked flights, hotels, day-by-day stops, route timing text, and imported expenses.",
    localReference: PORTUGAL_WANDERLOG_PDF_SOURCE,
    isSensitivePlaceholder: false,
  },
  {
    id: "portugal-booking-placeholders",
    tripId: "portugal-2026",
    fileName: "portugal-booking-confirmations-placeholder.pdf",
    type: "booking",
    note: "Metadata only. Add confirmation screenshots later without storing private documents in localStorage.",
    isSensitivePlaceholder: true,
  },
];

export const portugalRouteSuggestions: RouteSuggestion[] = [
  {
    id: "portugal-book-lagos-return",
    tripId: "portugal-2026",
    day: 9,
    severity: "warning",
    title: "Book Lagos to Lisbon transport",
    detail: "The Google Doc says to arrive in Lisbon before 8:00 PM on Jun 16 so Rachel's arrival morning stays easy.",
  },
  {
    id: "portugal-book-driver-transfer",
    tripId: "portugal-2026",
    day: 13,
    severity: "warning",
    title: "Confirm Lisbon to Porto driver day",
    detail: "Book the scenic transfer only after confirming luggage and keeping the stops to around Óbidos and Nazaré.",
  },
  {
    id: "portugal-book-douro",
    tripId: "portugal-2026",
    day: 15,
    severity: "warning",
    title: "Book Douro Valley tour",
    detail: "Pick a scenic day tour with lunch, viewpoints, and a river cruise. Keep dinner simple afterward.",
  },
  {
    id: "portugal-sintra-choice",
    tripId: "portugal-2026",
    day: 12,
    severity: "info",
    title: "Choose the Sintra combo",
    detail: "Regaleira plus Monserrate is the calmer plan. Add Pena only if the colorful palace is worth the crowds.",
  },
];

export const portugalTrip: Trip = {
  id: "portugal-2026",
  title: "Portugal Trip",
  country: "Portugal",
  startDate: "2026-06-08",
  endDate: "2026-06-24",
  currency: "EUR",
  currencyConfig: {
    localCurrency: "EUR",
    comparisonCurrency: "CAD",
    localPerCad: PORTUGAL_CAD_TO_EUR,
    label: "EUR per 1 CAD",
    isEstimate: true,
  },
  description: "A June 2026 Portugal route from Lisbon to Lagos, Sintra, Porto, and the Douro Valley, imported from the Google Doc PDF and Wanderlog PDF.",
  activities: portugalActivities,
  flights: portugalFlights,
  hotels: portugalHotels,
  attachments: portugalAttachments,
  notes: "Imported from /Users/nhihad/Downloads/Portugal_Mainland_Trip_Itinerary_June_2026.docx.pdf and /Users/nhihad/Downloads/Trip to Portugal – Wanderlog.pdf. Remaining booking focus: Lagos return transport, Lisbon-Porto driver day, Ponta da Piedade tour, Douro Valley tour, Sintra tickets, Gaia/cellar visit, special dinner, Livraria Lello.",
};
